---
title: "Working on Deliverables"
date: "2026-04-27"
categories:
  - Reading
  - Writing
  - Planning
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: April 27 - May 3, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   This week is all about making progress in my writing deliverables.

------------------------------------------------------------------------

<div>

> Monday - UW-RUA
>
> Tuesday - Finishing my Annual Evals
>
> Wednesday - Methylation & Biomarkers
>
> Thursday - Methylation
>
> Friday - Methylation and Biomarkers
>
> Saturday - No Science
>
> Sunday - Methylation

</div>

------------------------------------------------------------------------

### Plan of the Day

### *Granular level task list to accomplish the high- level goal outlined above*

-   My primary goals for today are as follows:
    -   Get my agenda items wrapped up for my meeting with Steven this
        morning - I am woefully behind.
    -   Knockout my UW-RUA Leadership Team meeting and deliverables
    -   Get my DML results worked up for discussion with Steven

### Projects Touched Today

-   Mussel Methylation

------------------------------------------------------------------------

### Progress Notes

-   I am far more overloaded than I expected. The best thing to happen
    this morning was pushing back my meeting with Steven until
    Wednesday.
-   I worked on the DML results via literature search, but didn't get my
    notes and outputs together.
-   The rest of the day was spent on RUA work.

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   Notes on DMLs: \~250 words

<div>

> **Today's total: 250 words**
>
> **Monthly total to date: 7455 words**
>
> **Annual total to date: 40,128 words**
>
> **Annual target total to date: 56,000 words**

</div>

### Next Up: Tomorrow's Plan

-   Will be determined during weekly planning.
