---
title: "Setting Up for the Upcoming Week"
date: "2026-04-26"
categories:
  - Reading
  - Writing
  - Planning
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: April 20 - April 26, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   This week is all about intertidal invertebrates, mussel methylation
    and pulling off the UW-RUA professional development programming
    series.

------------------------------------------------------------------------

<div>

> ~~Monday - 1v1 & Yellow Surveys~~
>
> ~~Tuesday - Yellow Surveys~~
>
> ~~Wednesday - UW-RUA & Event Prep~~
>
> ~~Thursday - UW-RUA Events & Methylation~~
>
> ~~Friday - UW-RUA Professional Development Full Day~~
>
> ~~Saturday - Methylation~~
>
> Sunday - Methylation

</div>

------------------------------------------------------------------------

### Plan of the Day

### *Granular level task list to accomplish the high- level goal outlined above*

-   My primary goals for today are as follows:
    -   Wrap-up yesterday's daily post... I totally forgot!
    -   Make notes on the papers I read yesterday
        -   More accurately, collate the notes I took and identify the
            gaps
    -   Map out this week's deliverables while I:
        -   Pull together my agenda for my Steven 1v1 on Tuesday, 4/28
        -   Pull together my agenda for my Julia 1v1 on Monday, 4/27

### Projects Touched Today

-   None

------------------------------------------------------------------------

### Progress Notes

-   I did things...

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   Something: 0 words

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 7205 words**
>
> **Annual total to date: 39,878 words**
>
> **Annual target total to date: 55,500 words**

</div>

### Next Up: Tomorrow's Plan

-   Will be determined during weekly planning.
