---
title: "Data Management, DNA Methylation, and ... "
date: "2026-03-27"
categories:
  - DNA Methylation
  - Chapter 3 
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: March 23 - 27, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   I am still not at full capacity and my plan for the week is to map
    out the rest of March and Spring Quarter since I have some very
    real, very important deadlines I'd like to hit.

------------------------------------------------------------------------

<div>

> ~~Monday - Catch up on UW-RUA and science project planning~~
>
> ~~Tuesday - Planning & biomarker manuscript work~~
>
> ~~Wednesday - Biomarker Manuscript~~
>
> ~~Thursday - Chapter 3 proposal~~
>
> Friday - Chapter 3 proposal
>
> Saturday - Biomarker Manuscript
>
> Sunday - Weekly planning and prep

</div>

------------------------------------------------------------------------

### Plan of the Day

#### *Granular level task list to accomplish the high- level goal outlined above*

-   Today's goal is to complete the followings:
    -   Backup my methylation data from Raven on Gannet
    -   Get my full sequence alignments running
    -   Outline Chapter 3 with research questions
        -   Finish review of bookmarked sequences
        -   Identify usable NCBI data sources and plan for them
        -   Identify other ways to integrate epigenetic mechanisms to
            make the chapter more robust

### Projects Touched Today

-   DNA Methylation
-   Chapter 3

------------------------------------------------------------------------

### Progress Notes

-   I have two meetings and a doctor's appointment today, spread out at
    the most inconvenient intervals, so my plan today is to knock out
    tasks and work that is easy to put down and pick back up.
-   First, I dropped into science hour to get Sam's help in completing
    the rsync from Raven to Gannet for my methylation repo.
    -   I cleaned up old files, removed old repos, and made sure to
        commit anything necessary to github via terminal instead of the
        interface before completing the sync.
    -   We also chatted about the difference in parameters used to align
        the methylation sequences. I'm going with the standard choice in
        the lab re: stringency since the outputs don't seem to show any
        significant differences.
-   Next I worked on creating the deduplication script for the full
    sequences (not just the two I was working on, and not just the first
    10k pairs) with a MultiQC output.
-   I reviewed the methylation extraction code from both Sam and Steven
    and started to put that together.
-   

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   SACNAS Abstract: 213 words
-   Something else: 0 words
-   Created scripts for the methylation analysis: 2 scripts

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 10,399 words**
>
> **Annual total to date: 32,094 words**
>
> **Annual target total to date: 43,000 words**

</div>

### Next Up: Tomorrow's Plan

-   Will be determined by the end of the day!
