---
title: "Biomarkers & Mentorship"
date: '2025-10-01'
categories:
  - biomarkers
  - mentorship
  - literature review
execute:
  echo: false
  warning: false
  message: false
---

-   Started with a re-run of my site comparisons for the biomarkers. I was writing the results and trying to make some sense of what wasn't sitting right, and it turns out that if you aren't using the correct df in your code, you get a p-value of 0.478 for every single metric you are looking at when trying to understand if there are differences by site...
-   Alison and I met to talk about the paper and how we're going to get the manuscript ready for the WIMS x ICB submission window time frame. I felt really good about it and I believe she's cautiously optimistic that we'll make it!
-   I had a wonderful conversation with Chelsea Wood today - scheduled - to discuss how to start curating my science brand and where to focus my professional development so that I'm not trying to slam in all of the work in my final year when I'm trying to apply for positions.
* I ended the day working on pulling lit on the efficacy of conservation ecology work. This proved to be very difficult to find since the dominant result was either about engineering, the role of specific species, or commentary on how conservation practices should work. I made a log of search terms, platforms, results returned and added about 30 papers that get close to my topic, but this is still not working as I wanted.
  * Ultimately, this makes me question how we get the siloed work of individual organizations aligned with the 'big data' that is being collected, or how we gain access or clarity around the data and action of the organizations. Trying to clarify the efficacy of conservation efforts is challenging, especially when we all define efficacy a bit different.
