---
title: "2025 September Daily Posts"
date: '2025-09-01'
toc: true
page-layout: article
format:
  html:
    df-print: paged
---

> This page compiles all daily posts for 2025-09.

### 2025-09-24 — New AY, New Set Up

In true to me fashion, a new academic year means a new notebook setup that will hopefully make it a bit easier for me to update my work daily. Today's science focus was on rebuilding, updating and launching my 2025-26 AY lab notebook. Related, I made a 'sprint' task list for quick tasks I can do to tighten up my GitHub setup, cleanup my repos, and identify any pinch points for making a daily update. My second focus was to setup weekly meetings with my PI and gather materials for my first meeting on 9.25.25.

### 2025-09-25 — Put Your \$\$ Where Your Mouth Is

-   Today's work fell in the broad category of preparing for lab meeting and the subsequent 1v1 with Steven. My main takeaways are to set explicit goals that we will share and work on in biweekly lab meetings.\
-   My goal for next lab working session is to have one of my three bypass chapters complete to the standard of the package and the other two fully outlined.\
-   Meeting with Steven post lab meeting we agreed that my AY goal, to become a candidate by the end of the year, is big but doable as long as I stay accountable to myself. Additionally, my deliverable from the meeting is to complete the SAFS milestones form and get it back to him by the end of the week.

### 2025-09-26 — Biomarkers, Back Again

-   My work today started with a quick audit of my GH repos and what should be cleaned up as I move forward. I added the tasks to my Notion management setup, separated in quick tasks and anything that will take longer than 30 minutes so I could manage getting a few things done where I can rather than try to knock out big chunks at a time.\
-   My primary work (deep work) focused on getting back to the biomarker work I set down before leaving for the summer. I reviewed my most recent analysis notes, the questions/ comments I made for myself, and then the analyses. I had a hard time evaluating what was most important to tackle first, so I spent some time listing out my decisions to get to the end analyses and what result mapped to what choice before I could really get my head back in the game. This helped me identify an error in my contaminant indices and note that I needed to re-link the curated literature review to the draft in the methods and discussion drafting.

### 2025-09-27 — Day Off

No science work was done today.

### 2025-09-28 — Biomarkers Literature Reconciliation

-   All of today's focus was in tidying up my notes and citations for the biomarker manuscript draft. I have left notes or comments for myself that are a little cryptic, or worse, tags that aren't as descriptive as I need. The goal was to ensure I have the right citations in the right places and identify anything that needs additional depth in citations (biomarker work is rich in practitioners) or needs a citation period. This took much longer than I anticipated, so I knocked off for the day after that.

### 2025-09-29 — Bypass & Biomarkers

-   Most of today's work focused on my science task management.
    -   I completed the overdue milestones in the new SAFS tracker. As soon as my committee signs the Docusigm, I can submit that and get off the 'bad kids list'.
    -   I sent out the scheduler for my first committee meeting of the quarter. That meeting will be between 10/7 - 10/17.
    -   I sent my 'degree work' explainer over to Manca. She is helping to connect me to her former colleagues at WWU, so I needed to write a paragraph about my work and ultimate dissertation topic for her to send - that took me a surprisingly long time to craft. That flagged my need to clarify my work in both my mind and in how I share it - part of my personal goals for the year.
    -   I spent the rest of my science admin time assessing and mapping my deliverables for the bypass package and working to identify where I will need help.
-   My biomarker work was in mapping my plots for the manuscript and trying to get some of those plots to look better. Even when plotting by site (74 of them) the plots are a bit crowded, so I was working on that.

### 2025-09-30 — It's Epigenetics, Baby

-   Tuesdays are typically days where minimal science will be done since my student assistance-ship is the dominant player, but for at least one hour every week this quarter I'll get some science in there!
    -   Steven's class focused on epigenetics is a literature review class where we learn foundational concepts in the discipline and then bring our own interesting literature to present while interacting with what implications this information could have on our own work.
    -   Today was the first class, so it was a familiarization, a chance to read a foundational paper, and work test run the GitHub workflow for the course.
