---
title: "Mussels, Mussels Everywhere + RUA"
date: '2026-01-20'
categories:
  - mussel pilot experiment 
  - mussel resazurin trial
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   mussel pilot experiment
-   mussel resazurin trial

### New Knowledge

Day 28. Mussel Check at 1354

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase may get us to 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 30 psu

-   Mortality

    -   Blue= 0

    -   Red= 2

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 25

        -   Red= 25

-   Feeding

    -   Mussels were fed using the same calculations and method as outlined on 12.31.25 except tissue mass has been reduced to 140g for total tissue weight in the remaining mussels.

### Old Tricks

-   Same as 1.18: Right back at it refining, aligning and ensuring my proposal is clear without getting too into the weeds. I'm super close to a draft that isn't totally embarrassing to share with the committee.

-   I finished up the experimental design at a balanced scale for outcomes and size. I met with Ariana this morning to chat about Resazurin as the metabolic measure rather than straight-up respiration testing if possible. The goal is to try it out on the pilot mussels and see if we can see a difference between the heat treated v 'control' ambient mussels. She helped me identify some key safeguards and 'insurances' when running this for the first time with these samples.

### Word Count (Productivity)

-   RUA working day
-   **Today's total: 0 words**
-   **Monthly total to date: 6744 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.
