---
title: "Moving forward with Mussel Methylation Analysis "
date: "2026-03-21"
categories:
  - Mussel Methylation
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: March 16 - 22, 2026

-   I am feeling marginally better, and since I didn't map the week on
    Sunday, the plan today is to keep it low key so I don't put myself
    back at square one.
-   ~~**Monday**: Map the week, catch up on UW-RUA work, confirm my
    spring/ summer tide schedule, build base histone and chromatin
    knowledge notes.~~
-   ~~**Tuesday**: UW-RUA work, no science.~~
-   ~~**Wednesday**: Return to epigenetic mechanisms to outline new
    Chapter 3 for my proposal.~~
-   ~~**Thursday**: Biomarker manuscript~~
-   ~~**Friday**: Biomarker manuscript~~
-   **Saturday**: Return to Chapter 3 outline and start drafting options
    for the introduction and methods.
-   **Sunday**: Continue Chapter 3 work.

Missing from the plan is the DNA Methylation work - it will be worked
into the other priorities as time permits, or be a focus for spring
break week next week.

### Plan of the Day

-   Today's goal is to work on my new Chapter 3 outline and keep pushing
    the methylation work forward

### Projects Touched Today

-   Mussel Methylation

### Progress Notes

-   The day started with running FastQC and MultiQC on the
    representative samples.
    -   I did not properly move the sequencer artifacts, so my QC rerun
        failed repeatedly until I realized it was because I needed to
        properly move those files and not adjust the code... that took a
        little too long.
    -   FastQC went well and reminded me that I need to ask again what
        some of the quality parameters mean in the broader
        analysis-impact pov.
    -   I spent the better part of the day checking why I was stuck in
        MultiQC purgatory... I am doing something wring because it
        should not take half a day to run MultiQC on 4 samples, but
        after some troubleshooting, I can't figure out what it is. I
        will ask for help on this one before I screw up something in the
        shared drives on Raven.
-   I moved over to trimming, bypassing MultiQC while keeping FastQC.
    -   Based on on the FastQC returns, the standard 20by at the
        beginning and end of the raw sequences makes sense. I see we use
        fastp, but TrimGalore is everywhere - I will try to sort out the
        differences or create a comparison at another less
        time-restricted moment.
    -   I completed trimming, reviewed those FastQC files (bypassing
        MultiQC until I can figure out where it is getting stuck), and
        moved on to grabbing the reference genome from NCBI and starting
        the alignment.
-   Once I started the alignment script, I let that run while I worked
    on some of my UW-RUA deliverables for the week.

### Products & Word Count

-   No tangible products today.

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 8638 words**
>
> **Annual total to date: 30,333 words**
>
> **Annual target total to date: 40,000 words**

</div>

### Tomorrow's Plan

-   No science on Sunday. I am exhausted, still taking my cold meds and
    hoping to shake this off for good.
