---
title: "Biomarkers, Back Again"
date: '2025-09-26'
categories:
  - biomarkers
  - analysis
  - repo management
  - literature management
execute:
  echo: false
  warning: false
  message: false
---

* My work today started with a quick audit of my GH repos and what should be cleaned up as I move forward. I added the tasks to my Notion management setup, separated in quick tasks and anything that will take longer than 30 minutes so I could manage getting a few things done where I can rather than try to knock out big chunks at a time.  
* My primary work (deep work) focused on getting back to the biomarker work I set down before leaving for the summer. I reviewed my most recent analysis notes, the questions/ comments I made for myself, and then the analyses. I had a hard time evaluating what was most important to tackle first, so I spent some time listing out my decisions to get to the end analyses and what result mapped to what choice before I could really get my head back in the game. This helped me identify an error in my contaminant indices and note that I needed to re-link the curated literature review to the draft in the methods and discussion drafting.