---
title: "Task Management is the Name of the Game"
date: "2026-04-09"
categories:
  - Planning
  - Task Management
  - Yellow Island
  - Mussel Biomarkers
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: April 6 - April 12, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   This week's plan is to continue to move forward with the methylation
    analysis, refresh mutual goals, expectations and priorities with
    Steven, and set goals for April.

------------------------------------------------------------------------

<div>

> ~~Monday - Planning the week & Setting April Goals~~
>
> ~~Tuesday - UW-RUA, No Science~~
>
> Wednesday - Friday: Will Outline post Steven 1v1
>
> Saturday - No Science
>
> Sunday - Reading

</div>

------------------------------------------------------------------------

### Plan of the Day

#### *Granular level task list to accomplish the high- level goal outlined above*

-   Get my crap together! I have a multi-car pileup of tasks across so
    many different science projects and personal projects that today is
    the day to knock out what I can, schedule or delegate what I can't,
    and to make a few prioritization decisions to align with some of my
    larger goals and deliverables.

### Projects Touched Today

-   All of them! No, seriously...
-   Yellow Island
-   Mussel Biomarkers

------------------------------------------------------------------------

### Progress Notes

-   Today started with knocking out some personal business. I bring it
    up because all of the 'hurry up and wait' gave me time to take a
    look at my brain dump task list from earlier this week, break down
    some of the multi-step tasks, identify what would or would not make
    the boat go faster.
    -   "Will it make the boat go faster?" is the fundamental question
        [Martin
        McElroy](https://whchambers.com/conversation-with-martin-mcelroy-mba-olympic-gold-medal-winning-coach-faster-podcast/#:~:text=He%20is%20also%20credited%20with%20creating%20the,on%20what%20he's%20learned%20over%20the%20years)
        asked of the British rowing team while they were going for (and
        attained) the gold medal in the 2000 Olympics.
        -   Are the preparations, decisions, or actions I'm making and
            taking making my boat go faster? Going back to one of my
            favorites, Nick Saban, he is all about the process, not the
            outcome. So when you put these together you get the
            reinforcement of the daily task of focusing on what makes a
            difference (McElroy), and a commitment to meeting the daily
            task with 100% (Saban).
        -   All that to say that today was a mini-reset and refocus on
            what makes my boat go faster.
    -   First up, I knocked out the logistics for the 5 tide series on
        Yellow.
        -   I made my ferry reservations, bought my tickets, pulled
            together my supply lists, touched base with the land steward
            to confirm the volunteers'/ interns' schedules for support,
            and verified transport times to and from the ferry landings.
            Made my next steps list for food and travel days, pulled out
            the gear I'll need to keep in the trunk, and blocked my
            travel time in addition to the tide survey times rather than
            having 24hr blocks on my calendar.
    -   Next up, I pivoted to some event management for the upcoming
        UW-RUA event's I'm coordinating.
        -   I followed that up with a touch-base style 'office hours'
            with a few travelers that need some additional support in
            getting their visits planned and on their way.
    -   Next on the list was a critical review of the biomarker
        manuscript. I keep making 'large' to-do's like 'write the
        abstract', rather than the actual steps. This took a long time
        to keep myself focused on the critical look rather than fixing
        the thing I put on the list. It yielded a coupe of pages of
        notes that feels a little daunting.
        -   I batched the type of notes into writing, citing, and
            clarifying. Any notes that don't fall into those categories
            are not a priority to get the work out.
        -   The clarifying section includes notes like, "lines 22-26
            state but don't explain the connection between legacy
            contaminants and climate- driven stressors." What is one
            sentence that ties these together?
        -   The citing section includes notes like, "line 31, 34, and 37
            have synthesized for the public report-level citations."
            What are the individual papers/ research that support this
            synthesis?
        -   The writing section includes notes like, "lines 242-249 is
            about the spatial pattern of the biomarkers, but not the
            spatial pattern of the contaminant classes that is clearer
            and statistically significant." This is where the results
            are misaligned; the contaminants are spatially significant,
            but the biomarker response is not, this is where the IBR and
            Contaminant Indices come into play - justify why these
            'scores' are important in the narrative by connecting the
            spatial analyses to the biomarkers.
    -   I attended Maya Groner's seminar and learned more about marine
        diseases than I thought! Some very interesting and 'pugilistic'-
        themed research going on in the Bering!
    -   

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   Biomarker manuscript critical review: \~800 words

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 921 words**
>
> **Annual total to date: 33,593 words**
>
> **Annual target total to date: 49,000 words**

</div>

### Next Up: Tomorrow's Plan

-   Something that will be clear by the end of the day...
