---
title: "Getting Back on Track"
date: '2026-03-02'
categories:
  - planning
  - mussel biomarkers
  - lab notebook
  - goal setting
execute:
  echo: false
  warning: false
  message: false
---

### Plan of the Day

-   Catch up with weekly planning and task management since I've been sick for the last two weeks.
-   Create March Goals and plan for attainment

### Projects Touched Today

-   Mussel Biomarkers
-   PhD Proposal
-   Lab Notebook

### Progress Notes

-   It feels like everything is a bit messy currently, so a dedicated session to untangle the projects and required outcomes was truly necessary.
-   I first worked on extending the timelines and required deliverables for my non-dissertation projects before pivoting to planning my dissertation work. I chose to do it this way so I could identify what kind of timeline my non-dissertation projects would require so I could either delegate or manage the tasks for myself.
-   I reviewed the current state of the biomarker manuscript and the PhD proposal and identified some steps to complete both projects.

### Products & Word Count

<div>

-   March Goals and Planning: 294 words

> **Today's total: 294 words**
>
> **March total: 294 words**
>
> **2026 total: 21,041 words**

</div>

### Tomorrow's Plan

-   Tuesday's are UW-RUA days, so the plan is to focus on my RUA deliverables only, returning my science on Wednesday.
