---
title: "Tasks and Meetings"
date: '2026-02-11'
categories:
  - meetings
  - planning and preparation
execute:
  echo: false
  warning: false
  message: false
---

### Plan of the Day

-   Advisor 1v1
-   Lab Meeting
-   Potential UG for lab

### Projects Touched Today

-   MS proposal

### Progress Notes

-   Weekly meeting with Steven. He wants me to add more more detail on the Chapter 2 approaches as well as a more expanded results expectation and research questions. Will work on that.
-   The rest of the agenda was a run- through of the statuses of current and upcoming with no additional steps.
-   Lab meeting did not yield any tasks or extra responsibilities
-   Met with the Bio undergrad about what they are looking to gain and looking to contribute. Based on skills and interests, I think I have a 2- prong plan where we can gain some skill exposure, and get them linked to some of the summer opportunities that align with their interests.

### Products & Word Count
         
<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 2,075 words**
>
> **Annual total to date: 14,953 words**

</div>


### Tomorrow's Plan

-   Tomorrow is pretty meeting heavy. I have 2 UW-RUA debrief meetings post traveler return, the NW CASC Info-session, the first of 3 ESA *Future-Proofing Your Science Career* sessions, and a meeting with a former mentee to work through the stats and visualizations for his capstone project featuring the data we collected on Yellow Island from 2023 - 24.

-   Specific steps in my own work will be determined post today's meetings.
