---
title: "Saturday- Something "
date: "2026-03-28"
categories:
  - Mussel Methylation
  - NWS Symposium
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: March 23 - 29, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   I am still not at full capacity and my plan for the week is to map
    out the rest of March and Spring Quarter since I have some very
    real, very important deadlines I'd like to hit.

------------------------------------------------------------------------

<div>

> ~~Monday - Catch up on UW-RUA and science project planning~~
>
> ~~Tuesday - Planning & biomarker manuscript work~~
>
> ~~Wednesday - Biomarker Manuscript~~
>
> ~~Thursday - Chapter 3 proposal~~
>
> ~~Friday - Chapter 3 proposal~~
>
> Saturday - Biomarker Manuscript
>
> Sunday - Weekly planning and prep

</div>

------------------------------------------------------------------------

### Plan of the Day

#### *Granular level task list to accomplish the high- level goal outlined above*

-   Today's goal is to knock out the first version of the NWS poster to
    ask for feedback early next week

### Projects Touched Today

-   DNA Methylation

-   NWS Symposium

------------------------------------------------------------------------

### Progress Notes

-   After going over the parameters that Sam and I talked about
    yesterday, I annotated the scripts so I wouldn't forget.
    -   I am still running the methylation analysis with the standard
        alignment parameters (L,0, -0.6) because this aligment
        stringency is the best balance between mapping efficiency and
        not inflating the CHH or CHG percentages; methylation percentage
        changes marginally (11.5% to 11.7%)
    -   Clarifying what I mean re: parameters below. When running
        Bismark and Bowtie2, the list of parameters below tell the
        programs what to do.
        -   First, The goal is to convert the reference genome to a
            bisulfite- ready version for alignment, and then Bowtie2
            aligns my sample sequences with the bisulfite- converted
            reference genome.
        -   Alignment 'matching' stringency. This parameter check was
            done on the first 10k sequences of the aligned test
            sequences (69M- high PAH and 272M- low PAH) scores ranging
            from L,0,-4 to L,-1,-0.6). This is basically a 'how many
            mismatches are too many' check - the smaller the number
            (more negative), the more relaxed the matching and
            potentially the driver behind mapping efficiency
            differences. L- linear function, first number is the
            intercept, second number is the slope. These are impacted by
            read length... will add read length thresholds as a later-
            knowledge project.
        -   Output order. The Reorder call just puts the outputs in the
            same order as the inputs and supports future
            troubleshooting. This is for organization/ file management.
        -   Quality score. The call to ignore-quals is just a way to
            bypass any PHRED/ quality scores and treat all of the
            sequences the same. This is a data management command.
        -   R1 and R2 are a team. The —no-mixed command tells Bowtie2 to
            keep sequence pairs together, when one aligns but the other
            does not, the whole thing has to go. This makes the mapping
            more conservative and supports downstream analysis/
            interpretation.
        -   Direction. Non-directional versus directional calls either
            release or restrict the directional library assumptions.
            Library prep should have preserved strand directionality and
            this is the default call for the program, so no need for
            changing up now!
        -   Discordancey. A no-discordant call forces the alignments to
            follow paired-end logic (supporting the —no-mixed command).
        -   Dovetail and maxins: next up to double check they are
            actually commands to ensure fragments and overlapping reads
            aren't discarded, but I have to double check that because
            all of the online resources use descriptions that are as
            clear as mud.
-   I shifted over to sketching out a few poster ideas, settling on one
    that is too conceptual, and returning to square one.

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   Bismark & Bowtie2 Command Breakdown: 578 words

<div>

> **Today's total: 578 words**
>
> **Monthly total to date: 10,977 words**
>
> **Annual total to date: 32,672 words**
>
> **Annual target total to date: 43,500 words**

</div>

### Next Up: Tomorrow's Plan

-   Taking the day off to hang out with the kid
