---
title: "Testing Resazurin Assay Protocols for Mussels"
date: '2026-01-25'
categories:
  - mytilus_pilot
  - benchwork
  - experiment_takedown
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today
- Mytilus pilot

### New Knowledge
- Resazurin trials with the mussels that have undergone the 30-day survivability testing; modified protocol, notes and experiment raw data are in the January 25th weekly post.

### Old Tricks
- The 30-day survivability test for mussels is completed today, actual day 32. The mussels not used for the resazurin trials were removed from their mesh bags, visually inspected for any signs of slow response or shell damage, and then frozen in the -80 for potential baseline biomarker work to inform the full mussel experiment.
- The tanks and equipment were taken down, cleaned and kept together since it is a short period of time between takedown and setup for the full experiment.

### Questions or Concerns?
- Following up with EH&S for guidance around tank/ physical space requirements. It has been 2 weeks; may need to reach out again and have SR and/ or Sam and Jon help get a response.
- Will chat with Sam re: the location of the Hazardous Waste labels.

### Tomorrow's Plan
- Continue working through resazurin results and protocol optimization.