---
title: "Biomarkers & UW-RUA"
date: "2026-04-16"
categories:
  - Mussel Biomarkers
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: April 13 - April 19, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   This week is all about biomarkers and methylation.

------------------------------------------------------------------------

<div>

> ~~Monday - Methylation, `methylKit` run~~
>
> ~~Tuesday - UW-RUA, biomarkers~~
>
> ~~Wednesday - Biomarkers~~
>
> Thursday - Biomarkers
>
> Friday - Task management & ferry to FH/ Yellow
>
> Saturday - Yellow Island Surveys
>
> Sunday - Yellow Island Surveys

</div>

------------------------------------------------------------------------

### Plan of the Day

### *Granular level task list to accomplish the high- level goal outlined above*

-   My primary goals for today are as follows:
    -   Continue working through the biomarker draft updates
    -   Knock out my personal appointments/ tasks before heading up to
        Yellow

### Projects Touched Today

-   Mussel Biomarkers

------------------------------------------------------------------------

### Progress Notes

-   I started the day with a coffee info-session for RUA.
-   Next I moved to my own appointments/ obligations.
-   Returning home to work on the biomarker draft. I worked on
    incorporating the updated paragraphs for both the results and the
    discussion.
    -   Results will need a stronger focus - it is still a 'list-like'
        section, not what we need here.
    -   Plots will be revisited once the draft is sound, but I did make
        a few notes on what should be added to what is currently in the
        doc - can be sorted after the committee gets it.
    -   The introduction feels too broad - going to work on scoping that
        a bit once the rest is in a better place.
    -   Edits, edits, edits - my junkyard doc is getting lengthy!

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   Editing biomarkers: ? words (I forgot to turn on track changes to
    get an accurate count)

<div>

> **Today's total: ? words**
>
> **Monthly total to date: 4694 words**
>
> **Annual total to date: 37,367 words**
>
> **Annual target total to date: 51,500 words**

</div>

### Next Up: Tomorrow's Plan

-   Biomarkers and heading up to Yellow.
