project:
  type: website

website:
  title: "Progress Makes a PhD"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: lab_notebook.qmd
        text: Lab Notebook
        menu: 
          - href: dailylog.qmd
          - href: weeklyupdates.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: false

editor: source

