---
title: "Integrating Epigenetic Mechanisms"
date: "2026-03-19"
categories:
  - Foundational Knowledge
  - Epigenetic Mechanisms, Chromatin
  - PhD Proposal
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: March 16 - 22, 2026

-   I am feeling marginally better, and since I didn't map the week on
    Sunday, the plan today is to keep it low key so I don't put myself
    back at square one.
-   ~~**Monday**: Map the week, catch up on UW-RUA work, confirm my
    spring/ summer tide schedule, build base histone and chromatin
    knowledge notes.~~
-   ~~**Tuesday**: UW-RUA work, no science.~~
-   ~~**Wednesday**: Return to epigenetic mechanisms to outline new
    Chapter 3 for my proposal.~~
-   **Thursday**: Biomarker manuscript
-   **Friday**: Biomarker manuscript
-   **Saturday**: Return to Chapter 3 outline and start drafting options
    for the introduction and methods.
-   **Sunday**: Continue Chapter 3 work.

Missing from the plan is the DNA Methylation work - it will be worked
into the other priorities as time permits, or be a focus for spring
break week next week.

### Plan of the Day

-   I originally slated time today to work on biomarkers, but I want to
    finish the chromatin work so I can mull over the mechanisms while
    working on the biomarker manuscript.
-   Today is chromatin's day to shine... again!
    -   Compile current notes, identify basic biology, any applicable
        marine invert knowledge, and develop some questions around the
        mechanism in the context of my work.
-   I did not get through finalizing my chromatin notes and outlining
    Chapter 3, so I'm going to focus on that before moving into
    Biomarker work.
    -   First, review existing notes. Second, pull the questions out and
        put them with the rest and format notes like the others. Third,
        use the questions and notes to identify alternate ways to work
        with open source data for Chapter 3.
-   After note taking, I will begin outlining a plan for Chapter 3.
    -   Pivoting to a bioinformatics chapter rather than a lab based one
        will allow me to make better decisions for the experiments, more
        strongly tie the mechanisms to the outcomes, and pull together
        the complete work cleanly.

### Projects Touched Today

-   PhD Proposal
-   Foundational Knowledge
-   DNA Methylation

### Progress Notes

-   I started by wondering how I ever made it out of Catholic school
    with this handwriting!
    -   My Chromatin notes are a bit all over the place, so after a
        quick review I identified some gaps I have in understanding. I'm
        filling those in as best as I can to knock out the cleaner
        notes.
    -   I moved my questions over to the running doc and realized that
        chromatin remodeling is possibly the most straightforward of all
        of the mechanisms.
-   When I shifted over to DNA methylation, I found myself with more
    analysis/ workflow questions than mechanistic questions.
    -   I pivoted to creating a more comprehensive checklist and process
        to follow for myself since it is easy for me to rattle a few
        high-level steps, but unpacking them has been a process.
    -   I then created a decision outline with some guiding questions
        for the analysis.
    -   For both I chose to start at the point of sequences in hand - I
        will need to go back and make a section for sampling/
        experimental design. Probably when I work on the methods for the
        manuscript.
    -   This exercise took an embarassingly long time, but really helped
        me get down to the 'bones' of the process and set myself up to
        comprehensively answer any questions with something more robust
        than "that's how my lab does it".
-   For all of my explainers/ note docs I am certain there is plenty of
    room to make them better, and when the time is appropriate, I will,
    but for now I need to get back to basics and reinforce information
    or decisions I have been treating as 'set-in-stone' facts.

### Products & Word Count

-   [Doc
    6](https://docs.google.com/document/d/12V6pyDkOy_DVWm-HfZjPhmLSLpN4xraSp_fZQYd9bzc/edit?usp=sharing)-
    Chromatin Explainer: 498 words
-   [Doc
    7](https://docs.google.com/document/d/1RYjvVwA3ndbcXuhn3vkNCmippMzOkZuoBj4b2hzIz1c/edit?usp=sharing)-
    DNA Methylation Analysis Checklist: 573 words
-   [Doc
    8](https://docs.google.com/document/d/14Lpd-y2T5Lp_uivo1BLYlhafrL46wIxYLOQWxGtIL9I/edit?usp=sharing)-
    DNA Methylation Analysis Decisions: 875 words

<div>

> **Today's total: 1946 words**
>
> **Monthly total to date: 8538 words**
>
> **Annual total to date: 30,233 words**
>
> **Annual target total to date: 39,000 words**

</div>

### Tomorrow's Plan

-   Something
