---
title: "Advisor Working Session: May 5, 2026"
date: 2026-05-04
---

------------------------------------------------------------------------

### Agenda

------------------------------------------------------------------------

1.  Updates
    1.  Biomarker manuscript
    2.  Methylation results and discussion
    3.  Instructor of Record App - PoE
    4.  UG support for bench work
2.  GSAR

------------------------------------------------------------------------

### Update 1.1: Biomarker manuscript

------------------------------------------------------------------------

> Status: Updated figures for the manuscript have been either created or identified. They can be found in this [notebook post](https://chrismantegna.github.io/labnotebook/daily_log/2026_05_02/).
>
> Next Steps: I'm working on the results re-write and then the discussion.

------------------------------------------------------------------------

### Update 1.3: PoE Instructor Application

------------------------------------------------------------------------

> Status: Secured references, identified courses with the highest likelihood of teaching, and building my application now.The [application call](https://drive.google.com/file/d/1lX1NiGxdNeK33BTqFN2VbKbjPbmqcrQf/view?usp=sharing) was sent to SAFS as a general message.
>
> Next Steps: Application is due May 18, 2026 at 5:00 pm with a provisional notice of June 1. If chosen, will teach rather than continue with RUA. In addition, I submitted for the open TA positions.

------------------------------------------------------------------------

### Update 1.2: Methylation results and discussion

------------------------------------------------------------------------

> Status: Added [result 'write-up'](https://docs.google.com/document/d/16nAc2tWBRlhLHobFN4HZ6ux-Y1yztOQRnXleWBvsCbs/edit?usp=sharing)to the methods write-up, and added some discussion points.
>
> Next Steps:Clean-up, support, and write- out in full.

------------------------------------------------------------------------

### Update 1.3: UG support for bench work/ Yellow

------------------------------------------------------------------------

> Status: Shared a Google calendar with Cole on May 1st. We are aligning availability for training. An additional, unplanned trip to Yellow on Sunday, May 3rd was a bit derailing but ultimately go the samples together that we needed.
>
> Next Steps: Verify what training the UGs need to work in the lab, and then get Cole setup with the protocols and a schedule.

------------------------------------------------------------------------

### Item 2: GSAR

------------------------------------------------------------------------

> Status: Completed the student portion. The file can be [found here](https://drive.google.com/drive/folders/1vSi5NLuvWfwmx2eTGe_QD9ukGDyk0jGY?usp=sharing).
>
> Next Steps: Review with you and submit via the instructions indicated on the form.

------------------------------------------------------------------------

### Deliverables for Next Week

------------------------------------------------------------------------

> Item Status:
>
> Next Steps:
