---
title: "Tuesday's are UW-RUA Days"
date: "2026-04-07"
categories:
  - Mussel Methylation
  - 1v1
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: April 6 - April 12, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   This week's plan is to continue to move forward with the methylation
    analysis, refresh mutual goals, expectations and priorities with
    Steven, and set goals for April.

------------------------------------------------------------------------

<div>

> ~~Monday - Planning the week & Setting April Goals~~
>
> Tuesday - UW-RUA, No Science
>
> Wednesday - Friday: Will Outline post Steven 1v1
>
> Saturday - No Science
>
> Sunday - Reading

</div>

------------------------------------------------------------------------

### Plan of the Day

#### *Granular level task list to accomplish the high- level goal outlined above*

-   Continue to move forward with the methylation analysis.
-   Finish filling in the Agenda for my 1v1 with Steven tomorrow.
-   Shift over to UW-RUA work for the remainder of the day. I have 8
    travelers in progress and a ton of programming information to lock
    in.

### Projects Touched Today

-   DNA Methylation

------------------------------------------------------------------------

### Progress Notes

-   Tuesday's are my only full- day, UW-RUA days. The rest of the week
    see's RUA tasks/ events sprinkled throughout.
-   In between those obligations, I worked on my agenda for my 1v1 with
    Steven and the GPC, finally rendered that this afternoon around 3:00
    pm to share.
-   At the end of the day, I managed to resolve my github merge problem
    with my smaller files on Raven and called it a day!

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   Something: 0 words

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 921 words**
>
> **Annual total to date: 33,593 words**
>
> **Annual target total to date: 48,000 words**

</div>

### Next Up: Tomorrow's Plan

-   Something that will be clear by the end of the day...
