---
title: "Advisor Working Session: April 15, 2026"
date: "2026-04-14"
categories:
  - 1v1
  - Working Session
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    code-fold: true
---

------------------------------------------------------------------------

### Agenda

------------------------------------------------------------------------

1.  Updates

    1.  Shifting 4/21 meeting (1030-1130) to Wednesday or Thursday of the same week

    2.  Biomarker Manuscript

    3.  Plan for Methylation Manuscript completion NLT June 10, 2026

    4.  Committee email re: status update

2.  Methylation Analysis Resources

3.  Today's Goals for Working Session

------------------------------------------------------------------------

### Updates: 1.1 - Shift April 21st Working Session

------------------------------------------------------------------------

> Due to a scheduling conflict with boat transportation from Yellow to the ferry, the current time of 10:30 am - 11:30 am on 4/21 will not work. Can we shift to any of the following:
>
> Wednesday, April 22nd at or after 1:00 pm
>
> Thursday, April 23rd between 10:30a - 2:00 pm

------------------------------------------------------------------------

### Updates: 1.2 - Biomarker Manuscript Draft

------------------------------------------------------------------------

> The correct link to the draft and visualizations is [here](https://drive.google.com/drive/folders/1se75vO0siKTq4Bu4R7wSmX-Aa72IUh2V?usp=drive_link). I shifted from personal Google Drive to UW Google Drive.
>
> Status: Need to review current draft and request edits.
>
> Deadline: April 17th.

------------------------------------------------------------------------

### Updates 1.3: Mussel Methylation Manuscript Weekly Plan

------------------------------------------------------------------------

> Current project status: Moving into `methylKit` analysis prior to annotation and enrichment. Goals for the week are listed below with the steps in [this doc](https://docs.google.com/document/d/1SS7A_QtXSo6sVQVn8HDAZNxIL5ok56xbxIspe0jR-8s/edit?usp=sharing).
>
> Week of April 12th: Reliably run `methylKit` and know the inputs are correct
>
> Week of April 19th: Analysis focus: Unite, QC and PCAs
>
> Week of April 26th: Understanding DMLs/ DMRs
>
> Week of May 3rd: Annotation + Biology
>
> Week of May 10th: Integrating Methylation, Biology and Contaminants
>
> Week of May 17th: Figures and Rough Draft
>
> Week of May 24th: Refinement and Gaps
>
> Week of May 31st: Polish and Committee Prep
>
> Week of June 7th: Final-ish Review and Submission to Committee for Feedback

------------------------------------------------------------------------

### Updates 1.4: Committee Update Email

------------------------------------------------------------------------

> Goal: Send out an update on April 17th with the biomarker draft attached.
>
> Email should include new timeline for methylation manuscript, tentative timeline for PhD proposal/ bypass package, what else?

------------------------------------------------------------------------

### Item 2: Methylation Analysis Resources

------------------------------------------------------------------------

> Here are the links to:
>
> -   [Repo](https://github.com/ChrisMantegna/wdfw_mussel_methylation)
>
> -   [Gannet](https://gannet.fish.washington.edu:5001/?launchApp=SYNO.SDS.App.FileStation3.Instance&launchParam=openfile%3D%252Fhome%252Fwdfw_mussel_methylation%252F&SynoToken=eqHazyiMJX42w "Access Link")
>
> -   [Progress Log](https://chrismantegna.github.io/labnotebook/project_log/mussel_methylation/process.html)
>
> -   [Questions](https://chrismantegna.github.io/labnotebook/project_log/mussel_methylation/questions.html)

------------------------------------------------------------------------

### Item 4: Goals for Today

------------------------------------------------------------------------

> My goals for today's working session are:
>
> 1.  Identify how these sessions should go. What is the best use of the time, how can I be prepared for subsequent sessions? What pieces are most useful to provide to Steven in advance of the meeting?
> 2.  Discuss and refine the plan for the methylation manuscript.
> 3.  Gain some clarity around daily check-in practice.

------------------------------------------------------------------------

### Session Wrap-Up & Goals for Next Week

------------------------------------------------------------------------

> Updates post-session
>
> 1.  April 21st meeting moved to a virtual meeting on April 20th at 9:30a due to my tide schedule limitations.
> 2.  Committee email w/ biomarker draft on April 17th solely focused on the biomarker work; request feedback and edits before 5/8. Will followup on 5/8 with next steps.
> 3.  Adjusting the methylation manuscript plan is to use [this DML table](https://github.com/RobertsLab/project-mytilus-methylation/blob/main/output/11-methylkit-klone/myDiff_1055p.tab), determine the number of DMLs (17), the number of DMLs that are annotated, and have a drafted methods and results prepared for out 4/20 meeting.
>     1.  Agenda with the deliverables will be prepared and sent to Steven no later than Sunday morning, 4/19.
> 4.  Next week during our working session we will review the drafted methods and results, choose the key result, and start framing the discussion.
