---
title: "Mussels, Mussels Everywhere"
date: '2026-01-19'
categories:
  - mussel pilot experiment 
  - mussel resazurin trial
  - mussel experimental design
  - proposal writing
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   mussel pilot experiment
-   mussel resazurin trial
-   mussel experimental design
-   proposal writing

### New Knowledge

Day 27. Mussel Check at 1630

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C increasing to 22° C

-   Salinity

    -   Blue= 28 psu

    -   Red= 29 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 26

        -   Red= 26

### Old Tricks

-   Same as 1.18: Right back at it refining, aligning and ensuring my proposal is clear without getting too into the weeds. I'm super close to a draft that isn't totally embarrassing to share with the committee.

-   I finished up the experimental design at a balanced scale for outcomes and size. I will be checking-in with Ariana later this afternoon to chat about Resazurin as the metabolic measure rather than straight-up respiration testing if possible. The goal is to try it out on the pilot mussels and see if we can see a difference between the heat treated v 'control' ambient mussels.

### Word Count (Productivity)

-   MS & PhD Proposal: 346 words
-   Experimental Design, Justification & Resazurin modified protocol/ questions: 1265
-   **Today's total: 1611 words**
-   **Monthly total to date: 6744 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.
