---
title: "Mussels and Proposal Work"
date: '2026-01-10'
categories:
  - mussel pilot experiment
  - MS proposal 
  - PhD proposal
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   Mussel pilot experiment
-   MS proposal
-   PhD proposal

### New Knowledge

Day 18. Mussel Check at 1624

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There is a smell to the tanks, but that has to be waste products since there are no mortalities.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 27 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

- Reviewed previous day's work in both proposals
- Total new words added across both proposals: 941

### Questions or Concerns?

-   None.

### Tomorrow's Plan

- Nothing concrete except for checking the mussels. 1/11 is Sunday.

-   Didn't complete today, so will move this to next week. Pull all of my pilot observations out of my notebook and into their own table. I will need this information to help guide the continuation of the experimental design for the larger experiment.

