---
title: "Working Session & Re-Focusing"
date: "2026-04-15"
categories:
  - 1v1
  - Mussel Methylation
  - Mussel Biomarkers
  - Yellow Island
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: April 6 - April 12, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   This week is all about biomarkers and methylation.

------------------------------------------------------------------------

<div>

> ~~Monday - Methylation, `methylKit` run~~
>
> ~~Tuesday - UW-RUA, biomarkers~~
>
> Wednesday - Biomarkers
>
> Thursday - Biomarkers
>
> Friday - Task management & ferry to FH/ Yellow
>
> Saturday - Yellow Island Surveys
>
> Sunday - Yellow Island Surveys

</div>

------------------------------------------------------------------------

### Plan of the Day

### *Granular level task list to accomplish the high- level goal outlined above*

-   My primary goals for today are as follows:
    -   Continue working through the biomarker draft updates
    -   1v1 with Steven
    -   Verify my supplies, working gear, and transportation are set for
        Yellow.

### Projects Touched Today

-   Mussel Biomarkers
-   Mussel Methylation
-   Yellow Island

------------------------------------------------------------------------

### Progress Notes

-   I started the day by making ferry reservations up through my 4th
    tide series. Holding off on the 5th series until I know if I need
    it.
-   I wrapped up UW-RUA tasks I couldn't get to yesterday.
-   Returned to Yellow work by verifying my survey sheets, guides, gear,
    and Rite in the Rain paper are all good to go for the last
    preparation steps on Thursday.
    -   Have to check the boxes in the office to see if I am out after
        this series.
-   Met with Steven for our first of this new style of working session.
    The key takeaways are:
    -   Biomarker draft to committee on 4/17 with a feedback deadline of
        5/8.
    -   Shifting the methylation manuscript timeline to to use [this DML
        table](https://github.com/RobertsLab/project-mytilus-methylation/blob/main/output/11-methylkit-klone/myDiff_1055p.tab),
        determine the number of DMLs (17), the number of DMLs that are
        annotated, and have a drafted methods and results prepared for
        out 4/20 meeting.
    -   An agenda with the deliverables will be prepared and sent to
        Steven no later than Sunday morning, 4/19.
    -   Next week during our working session we will review the drafted
        methods and results, choose the key result, and start framing
        the discussion.
-   Next up, I did a quick review of the DML table and associated
    outputs to ensure I have what I need to move forward with our plan.
    -   There are 17 DMLs using 55% difference and a q-value = 0.01.
        -   Difference= mean methylation of tx 0  - mean methylation of
            tx 1
        -   Q-value = false discovery rate
    -   When you put these parameters together, at these levels, we get
        biologically meaningful (%) and statistically sound (q) results.
    -   A later task is to play around with both to see what is the
        same, different, defensible.
    -   The annotated gene list is in [Steven's notebook
        post](https://sr320.github.io/tumbling-oysters/posts/36-merry/).
        A quick review shows the following:
        -   12 of 17 DMLs mapped to genes that are hypo-, hyper-
            methylated, or both.
        -   4 are hyper-methylated, 6 are hypo-methylated, and 2 have
            both instances.
        -   The magnitudes of methylation in either direction are the
            same.
        -   10/12 have a characterized gene function, and 2/10 are
            uncharacterized.
    -   A task for Friday will be to dig into the result a little deeper
        to understand what I am seeing.
-   I shifted to editing and reworking some of the results of the
    biomarker paper with a focus on:
    -   Shifting the results section from a laundry list to a key
        result, supporting results, and a brief section of non-results
        that were anticipated.
    -   Next, aligning the discussion with both the key results and the
        introduction.
        -   This was a bit surface as I already worked on aligning it
            with the introduction; fresh eyes and a critical editing
            pass will fix this tomorrow morning.
    -   I flagged a few pieces of information that will support a
        coherent read of the paper and deeper look should the committee
        decide. Since that was not the focus, or a strict necessity for
        the draft, only a list of notes was created before moving back
        to reinforcing the citations with the annotated pieces I took
        from the WDFW reports last week.
-   Finally, I wrapped up the day by making a priority list of 'first to
    tackle' edits for tomorrow morning, updated this post, and shifted
    to making sure my deliverables for tomorrow's meetings were ready so
    I didn't derail the morning by already running behind.

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   Biomarker edits to results: 274 words

<div>

> **Today's total: 274 words**
>
> **Monthly total to date: 4694 words**
>
> **Annual total to date: 37,367 words**
>
> **Annual target total to date: 51,000 words**

</div>

### Next Up: Tomorrow's Plan

-   Biomarkers, biomarkers, biomarkers!
