---
title: "Epigenetic Mechanisms- More Notetaking"
date: '2026-03-15'
categories:
  - PhD Proposal
  - Literature Review
execute:
  echo: false
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

### Plan of the Week: March 9 - 15, 2026

-   My goal this week has been to rest and figure out some low- effort
    ways to get back into the work groove without overextending;
    overdoing it has been prolonging my actual getting down to business.

### Plan of the Day

-   Today's plan is to clean up my notes from Friday and Saturday and
    identify where I have gaps in my understanding to direct my
    readings.

### Projects Touched Today

-   Foundational knowledge- epigenetic mechanisms
-   Literature Review

### Progress Notes

-   I continued the work outlined yesterday and created one additional
    document while diving a bit deeper into the literature from the
    search results on Friday and Saturday.

### Products & Word Count

-   Notes on epigenetic mechanisms
    -   [Doc
        4](https://docs.google.com/document/d/18j-PT_9V2FtiYRrvmwtLtzP2dytnwpdmnx_iKtzmZpg/edit?usp=sharing)-
        concept mapping the mechanisms to my research: 385 words

<div>

> **Today's total: 385 words**
>
> **Monthly total to date: 4758 words**
>
> **Annual total to date: 26,453 words**
>
> **Annual target total to date: 37,000 words**

</div>

### Tomorrow's Plan

-   Will be to plan out the week, keep it low key and start prioritizing my in- progress work.
