---
title: "2026 January Daily Posts"
date: "2026-01-01"
toc: true
page-layout: article
format:
  html:
    df-print: paged
---

> This page compiles ***all*** daily posts for the month.

## 2026-01-01

### Day 1 of 365: January Goals

### January Goals

1.  Finish these proposals and get them out to my committee by the end of the month for a chance at submitting a bypass package by the February deadline.
2.  Get the biomarker manuscript polished enough to go to WDFW for review and sign-off.

### Today's Work

-   Day 9. Mussel Check 1430

-   Visual tank inspections looked good for airflow and water clarity; clear reduction in food since yesterday. Mussels were still aggregated in their respective bags/ coolers. The airflow in blue remains a bit lower than in red. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= 15° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 25 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

## 2026-01-02

### Mussels and King Tides

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 10. Mussel Check at 0600

Visual tank inspections looked good for airflow and water clarity; continued reduction in food since yesterday. Mussels were still aggregated in their respective bags/ coolers. The airflow in blue remains a bit lower than in red. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= 15° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 25 psu

-   Mortality

    -   Blue= 0

    -   Red= 1

### Old Tricks

-   I will not be checking on the mussels on 1/3 since I'm leaving for the coast after this morning's check. I will check upon return on 1/4.

### Questions or Concerns?

-   None

### Tomorrow's Plan

-   Photograph the tides off of La Push and tidepool!

## 2026-01-03

### Quiluete Land & Coastal Wanderings

### Projects Touched Today

-   None

### New Knowledge

-   The Quiluete Resort is the perfect place to unplug and is central to awesome tidepooling for the night low tides.

### Old Tricks

-   Hiking along the coast during low tide feels like treasure hunting!

### Questions or Concerns?

-   None

### Tomorrow's Plan

-   Return home, check on my mussels, and prepare for the first day of the next quarter.

## 2026-01-04

### Mussels

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 12. Mussel Check at 1520

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. The airflow in blue remains a bit lower than in red. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= 15° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 3

    -   Red= 0

-   Of course 3 kick the bucket! I do not know if all died today or yesterday, but since they are the control temp, it feels odd but could be due to air flow. I swapped the air stones between Red and Blue after wiping both down. The stronger air stone is now in Blue, with the less strong in Red since adjusting flow didn't seem to make enough of a change.

### Old Tricks

-   Time to prep for the new quarter by updating calendars, planning time off and mapping daily goals.
-   One of my 2026 goals is to write at least 500 new words a day. Ultimately, those words have to be in projects that move my work and my professional presence forward. The word count doesn't include emails or task- based writing.
-   I may adjust that to include coding work, visualizations created, etc., since those all contribute to completing the deliverables in front of me.

### Questions or Concerns?

-   None

### Tomorrow's Plan

-   Review the status of my proposals and make a daily plan for completing the drafts this month.

## 2026-01-05

### Welcome to Winter Quarter

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 13. Mussel Check at 1049

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. The air stone swap seems to be ok. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= 15° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   Not a lot of science beyond the mussel check. Prepping for a RUA day tomorrow.

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Tuesdays are RUA days again this quarter, so only mussel checks.

## 2026-01-06

### Mussels & RUA

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 14. Mussel Check at 1700

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. The air stone swap is ok. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= Increasing from 15° C to 18° C

-   Salinity

    -   Blue= 28 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 2

    -   Red= 0

-   Partial water changes in both coolers. Salinity recheck

    -   Blue= 25 psu

    -   Red= 25 psu

### Old Tricks

-   Tuesday is a RUA workday.

### Questions or Concerns?

-   None

### Tomorrow's Plan

-   Continue to knockdown the lit notes for biomarkers and my proposals.

## 2026-01-07

### Mussels and Biomarker Manuscript Work

### Projects Touched Today

-   Mussel biomarkers
-   Mussel pilot experiment

### New Knowledge

Day 15. Mussel Check at 1558

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. The air stone swap seems to be ok. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 25 psu

    -   Red= 25 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Feeding

    -   Using the same calculations as on 12.31, a 400mL slurry was made and divided between Red and Blue, with slightly more going to Blue.

### Old Tricks

-   Returned to working on the manuscript for biomarkers. I cleaned up the methods and results sections to make them more succinct and separate from the discussion.

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Limited time tomorrow as the quarterly cross- institution RUA meetings are all morning with 'working groups' in the afternoon.

## 2026-01-08

### Mussels and RUA Working Groups

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 16. Mussel Check at 0915

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. The air stone swap seems to be ok. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 25 psu

    -   Red= 25 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   Full RUA day.

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Breakdown my daily plan to smaller bites. Even the smallest tasks are taking a lifetime, which is an indicator that I am making them too big.

## 2026-01-09 

### Mussels and MS Proposal Work

### Projects Touched Today

-   Mussel pilot experiment
-   MS proposal

### New Knowledge

Day 17. Mussel Check at 1628

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 25 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   Returned to the MS proposal draft and made significant progress on the literature review to help me write the introduction section in a way that is a bit preachy, but done.

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Pull all of my pilot observations out of my notebook and into their own table. I will need this information to help guide the continuation of the experimental design for the larger experiment.

-   Return to lit review/ note taking for biomarker manuscript. Progress I made there really helped me knock out the MS proposal intro and I will need to expand for the intro to the PhD proposal.

## 2026-01-10

### Mussels and Proposal Work

### Projects Touched Today

-   Mussel pilot experiment
-   MS proposal
-   PhD proposal

### New Knowledge

Day 18. Mussel Check at 1624

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There is a smell to the tanks, but that has to be waste products since there are no mortalities.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 27 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   Reviewed previous day's work in both proposals
-   Total new words added across both proposals: 941

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Nothing concrete except for checking the mussels. 1/11 is Sunday.

-   Didn't complete today, so will move this to next week. Pull all of my pilot observations out of my notebook and into their own table. I will need this information to help guide the continuation of the experimental design for the larger experiment.

## 2026-01-11

### Sunday - No Science Today

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 19. Mussel Check at 1429

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There remains a smell to the tanks, but that has to be waste products since there are no mortalities.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 25 psu

    -   Red= 27 psu

-   Mortality

    -   Blue= 1

    -   Red= 0

### Old Tricks

-   None

### Questions or Concerns?

-   None

### Tomorrow's Plan

-   Map the week ahead to include the following: continue work on the proposals and supplementary visuals for the biomarkers, finalize a draft experimental design to inform the PhD proposal.

## 2026-01-12

### Mussels and Proposals

### Projects Touched Today

-   Mussel pilot experiment
-   MS proposal
-   PhD proposal

### New Knowledge

Day 20. Mussel Check at 1209

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There remains a smell to the tanks, but that has to be waste products since there are no mortalities.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 27 psu

-   Mortality

    -   Blue= 1

    -   Red= 0

-   Partial Water Change completed for Blue and Red by emptying half of the existing water and adding fresh seawater.

    -   Salinity rechecked

        -   Blue= 25

        -   Red= 25

### Old Tricks

-   Writing, writing, writing. I continued to move forward with adding a better outline for Chapter 3 and 4 in the PhD proposal, went back and revised the introduction to the MS proposal, and reworked the biomarker manuscript discussion/ future directions to align a bit better with the intro and results.

### Word Count (Productivity)

-   Editing biomarker manuscript: 520 words
-   MS proposal writing: 140 words
-   PhD propsal writing: 131 words
-   **Today's total: 791 words**
-   **Monthly total to date: 1732 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Tomorrow is a RUA day, so no real science will be done.

## 2026-01-13

### Mussels and RUA

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 21. Mussel Check at 1017

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There smell is almost non- existent now.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C increasing to 20° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   None.

### Word Count (Productivity)

-   No science writing today
-   **Today's total: 0 words**
-   **Monthly total to date: 1732 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Continue to last of selected papers for my proposals, work on the experimental design constraints and scale.

## 2026-01-14

### Mussels and Proposals

### Projects Touched Today

-   Mussel pilot experiment
-   Mussel experimental design

### New Knowledge

Day 22. Mussel Check at 1752

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There remains a smell to the tanks, but that has to be waste products since there are no mortalities.

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 29 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Partial Water Change completed for Red by emptying half of the existing water and adding fresh seawater.

    -   Salinity rechecked
        -   Red= 26

-   Mussels were fed using the same calculations and method as outlined on 12.31.25 except tissue mass has been reduced to 170g for total tissue weight in the remaining mussels.

### Old Tricks

-   Today I brain dumped all of the experimental design thoughts I was having from both the planning and the reading. It is possible to maintain an experiment that has treatments that include two temps (elevated and control), two metal concentrations and two PAH or PCB concentrations with interactive treatments. There would be 15 treatments that way, including controls. A fully expanded setup would be 21+ and that is excessive for not just the information it may not yield, but for the costs associated.
-   Based on the 'streamlined' setup, I created a folder in Zotero that has all of the associated papers to support the experimental design and endpoints. This will be useful for both the MS proposal and the PhD proposal.

### Word Count (Productivity)

-   1 draft experimental design outline for MS proposal: \~400 words (handwritten across 6 pages, A4 size)
-   **Today's total: 400 words**
-   **Monthly total to date: 2132 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Continue writing proposals to get them to the committee sooner rather than later. It's getting too close to offer a fair window of return.

## 2026-01-15

### Mussels and Proposals

### Projects Touched Today

-   Mussel pilot experiment
-   PhD proposal
-   Mussel experiment planning

### New Knowledge

Day 23. Mussel Check at 1503

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Partial Water Change completed for Blue by emptying half of the existing water and adding fresh seawater.

    -   Salinity rechecked
        -   Blue= 25

### Old Tricks

-   Returned to the PhD proposal after working on mussel experiment design. Made good progress on writing the methods sections, objectives and research questions. I feel like I matched the tone of the rest of the proposal and the MS proposal.
-   I messaged with Sam and emailed with Jon Whittock re: tank help and any guidance he had on using contaminants in lab experiments. I followed that up with a phone call and subsequent email to EH&S re: anything other than physical lab requirements and waste disposal of water with metals/ contaminants in it.

### Word Count (Productivity)

-   PhD Proposal: 1340 words
-   **Today's total: 1340 words**
-   **Monthly total to date: 3472 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Same as yesterday. Continue writing proposals to get them to the committee sooner rather than later. It's getting too close to offer a fair window of return.

## 2026-01-16

### More Mussels and Proposals

### Projects Touched Today

-   Mussel pilot experiment
-   PhD proposal

### New Knowledge

Day 24. Mussel Check at 1121

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   Returned to the PhD proposal after working on mussel experiment design. Made good progress on writing the methods sections, objectives and research questions. I feel like I matched the tone of the rest of the proposal and the MS proposal. I continued with creating a shortened version for chapters 1 and 2, and read two papers that I previously only read the abstract for.

### Word Count (Productivity)

-   PhD Proposal: 1105 words
-   **Today's total: 1105 words**
-   **Monthly total to date: 4577 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Same as yesterday. Continue writing proposals to get them to the committee sooner rather than later. It's getting too close to offer a fair window of return.

## 2026-01-17

### Mussel Check and Errands

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

Day 25. Mussel Check at 1004

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   None. Lot of personal stuff to knockout today.

### Word Count (Productivity)

-   **Today's total: 0 words**
-   **Monthly total to date: 4577 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-18

### Mussel Check and... You Guessed it, Proposal Writing

### Projects Touched Today

-   Mussel pilot experiment
-   Proposal writing

### New Knowledge

Day 26. Mussel Check at 1137

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   Right back at it refining, aligning and ensuring my proposal is clear without getting too into the weeds. I'm super close to a draft that isn't totally embarrassing to share with the committee.

### Word Count (Productivity)

-   MS & PhD Proposal: 556 words
-   **Today's total: 556 words**
-   **Monthly total to date: 5133 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-19

### Mussels, Mussels Everywhere

### Projects Touched Today

-   Mussel pilot experiment
-   Mussel resazurin trial
-   Mussel experimental design
-   Proposal writing

### New Knowledge

Day 27. Mussel Check at 1630

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C increasing to 22° C

-   Salinity

    -   Blue= 28 psu

    -   Red= 29 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 26

        -   Red= 26

### Old Tricks

-   Same as 1.18: Right back at it refining, aligning and ensuring my proposal is clear without getting too into the weeds. I'm super close to a draft that isn't totally embarrassing to share with the committee.

-   I finished up the experimental design at a balanced scale for outcomes and size. I will be checking-in with Ariana later this afternoon to chat about Resazurin as the metabolic measure rather than straight-up respiration testing if possible. The goal is to try it out on the pilot mussels and see if we can see a difference between the heat treated v 'control' ambient mussels.

### Word Count (Productivity)

-   MS & PhD Proposal: 346 words
-   Experimental Design, Justification & Resazurin modified protocol/ questions: 1265
-   **Today's total: 1611 words**
-   **Monthly total to date: 6744 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-20

### Mussels, Mussels Everywhere + RUA

### Projects Touched Today

-   Mussel pilot experiment
-   Mussel resazurin trial

### New Knowledge

Day 28. Mussel Check at 1354

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase may get us to 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 30 psu

-   Mortality

    -   Blue= 0

    -   Red= 2

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 25

        -   Red= 25

-   Feeding

    -   Mussels were fed using the same calculations and method as outlined on 12.31.25 except tissue mass has been reduced to 140g for total tissue weight in the remaining mussels.

### Old Tricks

-   Same as 1.18: Right back at it refining, aligning and ensuring my proposal is clear without getting too into the weeds. I'm super close to a draft that isn't totally embarrassing to share with the committee.

-   I finished up the experimental design at a balanced scale for outcomes and size. I met with Ariana this morning to chat about Resazurin as the metabolic measure rather than straight-up respiration testing if possible. The goal is to try it out on the pilot mussels and see if we can see a difference between the heat treated v 'control' ambient mussels. She helped me identify some key safeguards and 'insurances' when running this for the first time with these samples.

### Word Count (Productivity)

-   RUA working day
-   **Today's total: 0 words**
-   **Monthly total to date: 6744 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-21

### Mussels, Mussels Everywhere + eDNA

### Projects Touched Today

-   Mussel pilot experiment
-   Kenya eDNA
-   Proposal writing

### New Knowledge

Day 29. Mussel Check at 1813

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase may get us to 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 28 psu

    -   Red= 29 psu

-   Mortality

    -   Blue= 0

    -   Red= 6

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 25

        -   Red= 25

### Old Tricks

-   Same as 1.18, 1.19, and 1.20: Right back at it refining, aligning and ensuring my proposal is clear without getting too into the weeds. I'm super close to a draft that isn't totally embarrassing to share with the committee. I have finally finished verifying my lit, polishing what I can and have setup a schedule-send email because I do not need to share what time I finished this...

-   I met with Mollie Ball to go over the nuances between standard eDNA metabarcoding and using it for analyzing gut contents. This was super helpful and I now have a better idea of how to get my bench protocols cleaned up a bit.

### Word Count (Productivity)

-   Proposals: 938
-   **Today's total: 938 words**
-   **Monthly total to date: 7682 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-22 

### Mussels & Biomarkers

### Projects Touched Today

-   Mussel pilot experiment
-   Mussel biomarkers

### New Knowledge

Day 30. Mussel Check at 1944

Visual tank inspections look ok-ish for airflow and water clarity; water is very cloudy in comparison to previous checks. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase may get us to 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 3

### Old Tricks

-   I had some personal obligations to knock out today, so my main productive activity was making the maps of the contaminant indices and IBRs for the supplement of the biomarker paper.

### Word Count (Productivity)

-   Maps Made: 16
-   **Today's total: 0 words**
-   **Monthly total to date: 7682 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-23

### More Mussels and Biomarkers

### Projects Touched Today

-   Mussel pilot experiment
-   Mussel biomarkers

### New Knowledge

Day 31. Mussel Check at 1709

Visual tank inspections look fine for airflow but not for water clarity. Water is cloudier than yesterday and in comparison to previous checks. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase may get us to 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 28 psu

-   Mortality

    -   Blue= 0

    -   Red= 7

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 25

        -   Red= 25

-   With today's mortalities, we have reached 19 out of 30 (\>50%) in the elevated temperature treatment. Since we were aiming for a full 30-days, including acclimation, this is great. 22° C, despite a ramp-up is the max over time. Potentially feeding every 5 days instead of 7, and tighter salinity management with more frequent water changes may also increase resilience to the higher temp.

### Old Tricks

-   The biomarker paper is my focus for editing, expanding the introduction to better scaffold the problem we are solving, and fixing the method's subsection for analysis was my focus today. I also worked out some tentative captions for the figures, based on feedback from Alison about which viz is most effective. I am super excited about it is shaping up.

### Word Count (Productivity)

-   Biomarker manuscript and figure captions: 2574 words
-   **Today's total: 2574 words**
-   **Monthly total to date: 10,256 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-24

### Mussels, Thy Name is Icarus

### Projects Touched Today

-   Mussel pilot experiment
-   Mussel biomarkers

### New Knowledge

Day 32. Mussel Check at 1246

Visual tank inspections look fine for airflow but not for water clarity. Water is CLOUDY. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase has pushed us past 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 28 psu

-   Mortality

    -   Blue= 0

    -   Red= 4

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 26

        -   Red= 26

-   With today's mortalities, we have reached 23 out of 30 (\>50%) in the elevated temperature treatment. Since we're notching daily mortalities now, I will run the Resazurin trial tomorrow, 1/25 to hopefully ensure some of the elevated temp mussels can also be tested.

### Old Tricks

-   The biomarker paper is my focus for editing, expanding the introduction to better scaffold the problem we are solving, and fixing the method's subsection for analysis was my focus today. I also worked out some tentative captions for the figures, based on feedback from Alison about which viz is most effective. I am super excited about it is shaping up.

### Word Count (Productivity)

-   Biomarker manuscript and figure captions: 2574 words
-   **Today's total: 2574 words**
-   **Monthly total to date: 10,256 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.

## 2026-01-25

### Testing Resazurin Assay Protocols for Mussels

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

-   Resazurin trials with the mussels that have undergone the 30-day survivability testing; modified protocol, notes and experiment raw data are in the [January 25th weekly post](https://chrismantegna.github.io/labnotebook/weekly/2026_0125/) and the [mytilus_pilot repo](https://github.com/ChrisMantegna/mytilus_pilot).

Day 33. Mussel Check and Experiment Take Down at 1020

Visual tank inspections look fine for airflow but not for water clarity. Water is CLOUDY. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase has pushed us past 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 27 psu

-   Mortality

    -   Blue= 0

    -   Red= 5

### Old Tricks

-   The 30-day survivability test for mussels is completed today, actual day 33. The mussels not used for the resazurin trials were removed from their mesh bags, visually inspected for any signs of slow response or shell damage, and then frozen in the -80 for potential baseline biomarker work to inform the full mussel experiment.
-   The tanks and equipment were taken down, cleaned and kept together since it is a short period of time between takedown and setup for the full experiment.

### Questions or Concerns?

-   Next week Need to-do's: Following up with EH&S for guidance around tank/ physical space requirements.
-   Will chat with Sam re: the location of the Hazardous Waste labels.

### Tomorrow's Plan

-   Continue working through resazurin results and protocol optimization.

## 2026-01-26

### Mytilus is the Main Character

### Projects Touched Today

-   Mussel pilot experiment
-   Mussel experiment planning

### New Knowledge

-   I updated the metadata and ImageJ measurements in the data tables for the pilot resazurin trial ran on Sunday (1/25).
-   Put together some experimental design options for the isotopes of PAHs or PCBs that we can use in the lab. [Cambridge Isotope Labs](https://isotope.com/polycyclic-aromatic-hydrocarbon-pah-standards-and-standard-mixtures/) has a good selection of isotopes that we can order at various price points ranging from \$150 on the lower end and well over \$2000 on the higher end.
-   In addition, the Cambridge Isotope Labs has a grant section that is an easy lift to potentially attain the chemicals for no cost.

### Old Tricks

-   Continued to update my literature review notes since determining many of those notes have been incorrectly discarded.

### Questions or Concerns?

None

### Tomorrow's Plan

-   Prep for a full RUA day and events, not much but task management will be done tomorrow.

## 2026-01-27

### STEM Socializing - No Science Today

### Projects Touched Today

No project work today. Tuesdays are UW-RUA days.

### New Knowledge

I held an event to explain what UW-RUA can do, what the postdocs and PhD-C's need to apply, and generally trying to facilitate conversations and getting to know each other beyond just asking about the program. I learned far more about engineering than I expected, but enjoyed the clarity into how different graduate programs work.

### Old Tricks

Data cleaning and analysis for the historic UW-RUA program (all three iterations) has been a nice way to keep my exploratory visualization skills up.

### Questions or Concerns?

No.

### Tomorrow's Plan

Fly home.

## 2026-01-28

### Document or it didn't happen..

### Projects Touched Today

-   Lab Notebook

    -   The goal of the work today is to get my daily and weekly lab notebook back up to date!

### New Knowledge

I created a new template that makes staging my daily and weekly posts much easier to create. My current system is to drop updates into Notion using a button, and that helps me remember days whwere one or two things were going on without a lot of detail, but this format may be an easier capture of the details that are important.

### Old Tricks

Thank goodness for the Notion setup or I would have forgotten all that has been done!

### Questions or Concerns?

Why did I keep pushing this off?!?! Definitely going to give it a better run in February.

### Tomorrow's Plan

Reviewing and updating my written proposals and figures for the biomarker manuscript will be the plan for the remainder of the week.

## 2026-01-29

### No Science Today

No science today. I am home until February 2nd.

## 2026-01-30 

### No Science Today

No science today. I am home until February 2nd.

## 2026-01-31 

### No Science Today

No science today. I am home until February 2nd.
