---
title: "Course work & Biomarkers"
date: '2025-10-03'
categories:
  - biomarkers
  - fish 510
draft: false
execute:
  echo: false
  warning: false
  message: false
---

-   Science solidly fell into task management and project analysis review today.
    -   First, I read over the papers for this week's FISH 510 and setup my course project in Notion. I added my deadlines, deliverables and tasks and linked the literature for the course to the full project page.
    -   Second, I started answering the Discussion Questions for the week and looking ahead to the upcoming week. The goal is to post responses to the discussion questions for the following week by Thursday of the week we're in. I missed the mark this week, but it shouldn't be difficult moving forward.
-   I worked on wrapping up the biomarker analysis validation and documenting what steps and decisions I made in data manipulation, statistical analysis choices, and my interpretations of the individual results while thinking through what the results mean all together.
