---
title: "UW-RUA Tuesday"
date: '2026-03-17'
categories:
  - Lab Notebook
  - Yellow Island
execute:
  echo: false
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

### Plan of the Week: March 16 - 22, 2026

-   I am feeling marginally better, and since I didn't map the week on
    Sunday, the plan today is to keep it low key so I don't put myself
    back at square one.
-   ~~**Monday**: Map the week, catch up on UW-RUA work, confirm my
    spring/ summer tide schedule, build base histone and chromatin
    knowledge notes.~~
-   **Tuesday**: UW-RUA work, no science.
-   **Wednesday**: Return to epigenetic mechanisms to outline new
    Chapter 3 for my proposal.
-   **Thursday**: Biomarker manuscript
-   **Friday**: Biomarker manuscript
-   **Saturday**: Return to Chapter 3 outline and start drafting options
    for the introduction and methods.
-   **Sunday**: Continue Chapter 3 work.

Missing from the plan is the DNA Methylation work - it will be worked
into the other priorities as time permits, or be a focus for spring
break week next week.

### Plan of the Day

-   Tuesday's are UW-RUA days, no deep work done today.
-   Update weekend lab notebook posts.

### Projects Touched Today

-   Lab Notebook
-   Yellow Island

### Progress Notes

-   Today I pulled my notes and updated my daily lab notebook posts from
    the weekend and Monday.
-   I was able to confirm my spring/ summer tide schedule on Yellow and
    working with local sites. I submitted my schedule and needs on
    Monday and received very quick feedback from TNC today!

### Products & Word Count

-   No products today

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 5597 words**
>
> **Annual total to date: 27,292 words**
>
> **Annual target total to date: 38,000 words**

</div>

### Tomorrow's Plan

-   I was unable to get to my chromatin explainer on Monday, so that
    will be on the agenda along with developing an outline for Chapter 3
    that incorporates some of the questions I've been kicking around.
