---
title: "Meetings & Methylation"
date: "2026-04-08"
categories:
  - Lab Meeting
  - 1v1
  - Mussel Methylation
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: April 6 - April 12, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   This week's plan is to continue to move forward with the methylation
    analysis, refresh mutual goals, expectations and priorities with
    Steven, and set goals for April.

------------------------------------------------------------------------

<div>

> ~~Monday - Planning the week & Setting April Goals~~
>
> ~~Tuesday - UW-RUA, No Science~~
>
> Wednesday - Friday: Will Outline post Steven 1v1
>
> Saturday - No Science
>
> Sunday - Reading

</div>

------------------------------------------------------------------------

### Plan of the Day

#### *Granular level task list to accomplish the high- level goal outlined above*

-   Continue to move forward with the methylation analysis.
-   Lab and 1v1 Meetings

### Projects Touched Today

-   Mussel Methylation

------------------------------------------------------------------------

### Progress Notes

-   Today started with lab meeting where we shared updates and discussed
    lab equipment that could be purchased.
-   Next, I added the updated biomarker manuscript visuals to the shared
    Google Drive folder.
-   I met with Steven and Chelsea to go over the a plan to put these
    alerts in the rearview.
    -   I followed up with an email outlining what we discussed in the
        second half of the meeting.
    -   I set up 1- hour working blocks with Steven up through the week
        of May 11th.
    -   I put my project log together for the methylation analysis, so
        we had a jumping- off place beyond just an agenda of next steps.
-   I shifted over to working on the methylKit markdown for the next
    steps in the methylation analysis.
    -   Before getting to that, I looked up the DSS package that is the
        newer analysis package.
        -   It is a package specifically (as far as I can see) for
            assessing DMLs and DMRs...
        -   Fun find- Roberts Lab alum, Professor Yaamini Venkataraman's
            [lab notebook
            post](https://yaaminiv.github.io/Hawaii-Gigas-Methylation-Analysis-Part17/)
            about using DSS for analysis.
        -   methylKit 'DSS' applications can be found
            [here](https://rdrr.io/bioc/methylKit/man/calculateDiffMethDSS-methods.html),
            and DSS applications can be found
            [here](https://bioconductor.org/packages/release/bioc/html/DSS.html).
        -   A paper outlining the application can be found
            [here](https://pmc.ncbi.nlm.nih.gov/articles/PMC8171293/).
        -   I added both the package bookmark to my project bookmarks
            folder, and the paper to my bioinformatics library in Zotero
            before moving back to my methylKit work.
    -   In the process of looking at the DSS v methylKit packages, I
        came across a [DNA Methylation workflow
        tutorial](https://nbis-workshop-epigenomics.readthedocs.io/en/latest/content/tutorials/methylationSeq/Seq_Tutorial.html).
        I haven't really looked at it yet - that is a weekend task when
        I'm not trying to wrap my head around how to work through some
        of the other steps.
    -   Getting back on task, I started by building a proper metadata
        table. This didn't take long, but is definitely important for
        this leg of the work.
        -   I took my sample PAH classifications ranked from 1-6, the
            PAH concentrations, my site names, sample names, and then
            added treatment (0=low, 1=high) and a replicates column in
            case it will be needed later to existing data.
    -   Next I took the markdowns from the oly-repo in the lab handbook
        and created my methylkit files (4 total) following the same
        format and replacing the paths/ object names/ etc. that aren't
        applicable.
        -   Some of the parameter choices in the DML and DMR files are
            unclear at the moment and will be added to my running list
            of Steven questions. Nothing in the initial file import or
            qc work is unclear, so I'm going to go with it and annotate
            where I have questions after ensuring I have working code.
        -   Before I get really rolling, I need to add a few lines re:
            directory outputs for the objects and plots, so I did that
            in the console rather than in the markdowns.
    -   I made notes in the markdowns about what I need to do next, and
        will get back to it tomorrow.

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   methylKit markdowns: 4 scripts

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 921 words**
>
> **Annual total to date: 33,593 words**
>
> **Annual target total to date: 48,500 words**

</div>

### Next Up: Tomorrow's Plan

-   Something that will be clear by the end of the day...
