---
title: "Reading, Reading & More Reading"
date: '2025-10-04'
categories:
  - literature reconciliation
  - biomarkers
draft: false
execute:
  echo: false
  warning: false
  message: false
---

- All science today was in the reading and re-reading of the literature behind the biomarker work. I have a Zotero project with almost 100 papers in it that are at various levels of annotation and note taking. Not ideal.
  - I updated my sync to Notion by removing the complete project, selecting the papers I knew were 100% going to be cited, and then started triaging the mess I made to date.
  - Next, I made a holding folder for papers that may support very specific analysis decisions and papers that will support specific text in the manuscript.
  - Finally, I refined my note taking template to make the necessary information visible in a database in Notion so that when I want to review all papers supporting methods or my introduction or whatever, I can just sort and see my notes rather than have to open and close each individual entry to create another document that can get lost.