---
title: "Testing Resazurin Assay Protocols for Mussels"
date: '2026-01-25'
categories:
  - mussel pilot experiment
  - benchwork
  - experiment takedown
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   Mussel pilot experiment

### New Knowledge

-   Resazurin trials with the mussels that have undergone the 30-day survivability testing; modified protocol, notes and experiment raw data are in the [January 25th weekly post](https://chrismantegna.github.io/labnotebook/weekly/2026_0125/) and the [mytilus_pilot repo](https://github.com/ChrisMantegna/mytilus_pilot).

Day 33. Mussel Check and Experiment Take Down at 1020

Visual tank inspections look fine for airflow but not for water clarity. Water is CLOUDY. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase has pushed us past 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 27 psu

-   Mortality

    -   Blue= 0

    -   Red= 5

### Old Tricks

-   The 30-day survivability test for mussels is completed today, actual day 33. The mussels not used for the resazurin trials were removed from their mesh bags, visually inspected for any signs of slow response or shell damage, and then frozen in the -80 for potential baseline biomarker work to inform the full mussel experiment.
-   The tanks and equipment were taken down, cleaned and kept together since it is a short period of time between takedown and setup for the full experiment.

### Questions or Concerns?

-   Next week Need to-do's: Following up with EH&S for guidance around tank/ physical space requirements.
-   Will chat with Sam re: the location of the Hazardous Waste labels.

### Tomorrow's Plan

-   Continue working through resazurin results and protocol optimization.
