---
title: "No April Goal Setting"
date: "2026-04-01"
categories:
  - NWS Straits Symposium
  - Mussel Methylation
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: March 30 - April 5, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   I am finally as close to healthy as I have been in awhile, so as
    long as the anxiety of being so behind doesn't take me out, I will
    be solid!

------------------------------------------------------------------------

<div>

> ~~Monday - Catch up on UW-RUA and NWS Poster~~
>
> ~~Tuesday - UW-RUA, No Science~~
>
> Wednesday - Biomarker Manuscript
>
> Thursday - Biomarker Manuscript
>
> Friday - NWS Symposium
>
> Saturday - Biomarker Manuscript
>
> Sunday - No Science

</div>

------------------------------------------------------------------------

### Plan of the Day

#### *Granular level task list to accomplish the high- level goal outlined above*

-   There are no goals nor plan for today. Nothing like being derailed
    because your brain cannot get out of the death- cycle of replaying
    everything.
-   Goals for the month will be posted before the end of the week and
    today's working sessions will be dedicated to knocking out the mile-
    long list of UW-RUA tasks I have right now.

### Projects Touched Today

-   DNA Methylation
-   NWS Symposium

------------------------------------------------------------------------

### Progress Notes

-   Today packed a 1-2 punch across two very important axes of my life
    at current. Since deep work is almost impossible, I will move
    forward with task management.
    -   First, finalized and submitted the poster overview of the
        outcomes of conservation opportunities.
        -   I doubt I'll be able to present it, but at least now it is
            complete in case I can.
    -   Second, I had to clear out the remainder of my schedule for more
        pressing appointments, so that just feels like kicking the can
        down the road...
        -   The can will be kicked further down the road based on some
            department- level information.
    -   In my task processing, I was able to inspect and restart the
        methylation analysis.
        -   Sample 95, amongst the last to be aligned, has failed twice.
            The first time was due to a disconnection, and the second
            time is because I didn't clean out the temporary BAM files
            and it was skipped as already aligned.
        -   I properly cleaned up the repo, synced it to Gannet, and
            restarted the script.
    -   The remainder of the day was doing nothing but knocking out
        tasks mostly unrelated to science.

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   No science products

<div>

> **Today's total: 0 words**
>
> **Monthly total to date: 0 words**
>
> **Annual total to date: 32,672 words**
>
> **Annual target total to date: 45,500 words**

</div>

### Next Up: Tomorrow's Plan

-   I have back to back obligations in and out of the home, Connor's
    defense, and depending on my capacity, we shall see what can be
    done.
