---
title: "Chromatin's Turn to Shine"
date: '2026-03-18'
categories:
  - Foundational Knowledge
  - Epigenetic Mechanisms, Chromatin
  - PhD Proposal
execute:
  echo: false
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

### Plan of the Week: March 16 - 22, 2026

-   I am feeling marginally better, and since I didn't map the week on
    Sunday, the plan today is to keep it low key so I don't put myself
    back at square one.
-   ~~**Monday**: Map the week, catch up on UW-RUA work, confirm my
    spring/ summer tide schedule, build base histone and chromatin
    knowledge notes.~~
-   ~~**Tuesday**: UW-RUA work, no science.~~
-   **Wednesday**: Return to epigenetic mechanisms to outline new
    Chapter 3 for my proposal.
-   **Thursday**: Biomarker manuscript
-   **Friday**: Biomarker manuscript
-   **Saturday**: Return to Chapter 3 outline and start drafting options
    for the introduction and methods.
-   **Sunday**: Continue Chapter 3 work.

Missing from the plan is the DNA Methylation work - it will be worked
into the other priorities as time permits, or be a focus for spring
break week next week.

### Plan of the Day

-   Today is chromatin's day to shine!
    -   Compile current notes, identify basic biology, any applicable
        marine invert knowledge, and develop some questions around the
        mechanism in the context of my work.
-   Format and render my lab notebook posts so they look less like an
    unhinged diary...

### Projects Touched Today

-   Lab Notebook
-   PhD Proposal
-   Foundational Knowledge

### Progress Notes

-   I caught up the notebook posts, archived February's posts to a
    single doc, and added a few images to make things more fun!
-   I started by prepping for my afternoon meetings
    -   UW-RUA applicants X 2 re: research statement feedback
    -   NW Straits April 3rd Caroline Gibson 'Conference' prep re:
        posters and abstract submission guidelines
    -   Henry Art Gallery re: my written accompaniment piece for a
        summer showcase
    -   Alternate paths to marine science for a high school group
        related to the IG cohort
-   I completed a one- pager for a STEM/social science collaboration in
    late 2026/ early 2027 if accepted
-   I completed the initial pass on the chromatin explainer, but found
    that it is mostly questions and connections to histones (obviously),
    so this may be the shorted explainer yet!
    -   Once I clean this up, I will add it to the digital notes but
        right now my handwritten notes are all over the place.
    -   Next steps are to put all three mechanisms together and make a
        plan for how to use current open source data to develop an
        analysis plan.

### Products & Word Count

-   Building Bridges in Conservation: 765 words
-   Chromatin raw notes (handwritten): 230 words

<div>

> **Today's total: 995 words**
>
> **Monthly total to date: 6592 words**
>
> **Annual total to date: 28,287 words**
>
> **Annual target total to date: 38,500 words**

</div>

### Tomorrow's Plan

-   Clean up chromatin notes and add to epigenetics explainers in my
    foundational knowledge db.

-   Pivot to using the notes to create a plan for Chapter 3.

-   Review biomarker manuscript and make a plan for completion.
