---
title: "Mussels and Proposals"
date: '2026-01-15'
categories:
  - mussel pilot experiment
  - PhD proposal
  - mussel experiment planning
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   mussel pilot experiment
-   PhD proposal
- mussel experiment planning

### New Knowledge

Day 23. Mussel Check at 1503

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. 

-   Temperature

    -   Blue= 11° C

    -   Red= 20° C

-   Salinity

    -   Blue= 27 psu

    -   Red= 26 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Partial Water Change completed for Blue by emptying half of the existing water and adding fresh seawater.

    -   Salinity rechecked
        -   Blue= 25

### Old Tricks

- Returned to the PhD proposal after working on mussel experiment design. Made good progress on writing the methods sections, objectives and research questions. I feel like I matched the tone of the rest of the proposal and the MS proposal. 
- I messaged with Sam and emailed with Jon Whittock re: tank help and any guidance he had on using contaminants in lab experiments. I followed that up with a phone call and subsequent email to EH&S re: anything other than physical lab requirements and waste disposal of water with metals/ contaminants in it. 

### Word Count (Productivity)

-   PhD Proposal: 1340 words
-   **Today's total: 1340 words**
-   **Monthly total to date: 3472 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Same as yesterday. Continue writing proposals to get them to the committee sooner rather than later. It's getting too close to offer a fair window of return.
