---
title: "Mussels and Proposals"
date: '2026-01-14'
categories:
  - mussel pilot experiment
  - mussel experimental design
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   mussel pilot experiment
-   mussel experimental design

### New Knowledge

Day 22. Mussel Check at 1752

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There remains a smell to the tanks, but that has to be waste products since there are no mortalities.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C increasing to 20° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 29 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Partial Water Change completed for Red by emptying half of the existing water and adding fresh seawater.

    -   Salinity rechecked
        -   Red= 26

-   Mussels were fed using the same calculations and method as outlined on 12.31.25 except tissue mass has been reduced to 170g for total tissue weight in the remaining mussels.

### Old Tricks

-   Today I brain dumped all of the experimental design thoughts I was having from both the planning and the reading. It is possible to maintain an experiment that has treatments that include two temps (elevated and control), two metal concentrations and two PAH or PCB concentrations with interactive treatments. There would be 15 treatments that way, including controls. A fully expanded setup would be 21+ and that is excessive for not just the information it may not yield, but for the costs associated.
-   Based on the 'streamlined' setup, I created a folder in Zotero that has all of the associated papers to support the experimental design and endpoints. This will be useful for both the MS proposal and the PhD proposal.

### Word Count (Productivity)

-   1 draft experimental design outline for MS proposal: \~400 words (handwritten across 6 pages, A4 size)
-   **Today's total: 791 words**
-   **Monthly total to date: 2132 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Continue writing proposals to get them to the committee sooner rather than later. It's getting too close to offer a fair window of return.
