---
title: "Mytilus is the Main Character"
date: '2026-01-26'
categories:
  - mussel pilot experiment
  - mussel experiment planning and design
  - data analysis 
  - resazurin
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

- Mussel pilot experiment 
- Mussel experiment planning

### New Knowledge

-   I updated the metadata and ImageJ measurements in the data tables for the pilot resazurin trial ran on Sunday (1/25).
-   Put together some experimental design options for the isotopes of PAHs or PCBs that we can use in the lab. [Cambridge Isotope Labs](https://isotope.com/polycyclic-aromatic-hydrocarbon-pah-standards-and-standard-mixtures/) has a good selection of isotopes that we can order at various price points ranging from \$150 on the lower end and well over \$2000 on the higher end.
- In addition, the Cambridge Isotope Labs has a grant section that is an easy lift to potentially attain the chemicals for no cost.

### Old Tricks
- Continued to update my literature review notes since determining many of those notes have been incorrectly discarded.

### Questions or Concerns?
None

### Tomorrow's Plan
- Prep for a full RUA day and events, not much but task management will be done tomorrow.
