---
title: "Mussels and MS Proposal Work"
date: '2026-01-09'
categories:
  - mussel pilot experiment
  - MS proposal 
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   Mussel pilot experiment
-   MS proposal

### New Knowledge

Day 17. Mussel Check at 1628

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 25 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

### Old Tricks

-   Returned to the MS proposal draft and made significant progress on the literature review to help me write the introduction section in a way that is a bit preachy, but done.

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Pull all of my pilot observations out of my notebook and into their own table. I will need this information to help guide the continuation of the experimental design for the larger experiment.

-   Return to lit review/ note taking for biomarker manuscript. Progress I made there really helped me knock out the MS proposal intro and I will need to expand for the intro to the PhD proposal.
