---
title: "Mussels and Proposals"
date: '2026-01-12'
categories:
  - mussel pilot experiment
  - MS proposal
  - PhD proposal 
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   mussel pilot experiment
-   MS proposal
-   PhD proposal

### New Knowledge

Day 20. Mussel Check at 1209

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. There remains a smell to the tanks, but that has to be waste products since there are no mortalities.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 26 psu

    -   Red= 27 psu

-   Mortality

    -   Blue= 1

    -   Red= 0

-   Partial Water Change completed for Blue and Red by emptying half of the existing water and adding fresh seawater.

    -   Salinity rechecked

        -   Blue= 25

        -   Red= 25

### Old Tricks

-   Writing, writing, writing. I continued to move forward with adding a better outline for Chapter 3 and 4 in the PhD proposal, went back and revised the introduction to the MS proposal, and reworked the biomarker manuscript discussion/ future directions to align a bit better with the intro and results.

### Word Count (Productivity)

-   Editing biomarker manuscript: 520 words
-   MS proposal writing: 140 words
-   PhD propsal writing: 131 words
-   **Today's total: 791 words**
-   **Monthly total to date: 1732 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Tomorrow is a RUA day, so no real science will be done.
