---
title: "Mussels and Biomarker Manuscript Work"
date: '2026-01-07'
categories:
  - mussel biomarkers
  - mussel pilot experiment 
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   Mussel biomarkers
-   Mussel pilot experiment

### New Knowledge

Day 15. Mussel Check at 1558

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. The air stone swap seems to be ok. Will continue to monitor.

-   Temperature

    -   Blue= 11° C

    -   Red= 18° C

-   Salinity

    -   Blue= 25 psu

    -   Red= 25 psu

-   Mortality

    -   Blue= 0

    -   Red= 0

-   Feeding

    -   Using the same calculations as on 12.31, a 400mL slurry was made and divided between Red and Blue, with slightly more going to Blue.

### Old Tricks

-   Returned to working on the manuscript for biomarkers. I cleaned up the methods and results sections to make them more succinct and separate from the discussion.

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Limited time tomorrow as the quarterly cross- institution RUA meetings are all morning with 'working groups' in the afternoon.
