---
title: "Booked & Busy"
date: '2025-10-06'
categories:
  - lab meeting
  - bypass presentation
draft: false
execute:
  echo: false
  warning: false
  message: false
---

-   Attended lab meeting where we shared our bi-weekly goals, progress, knowledge nuggets, and upcoming goals. My responses are below. My goals are built off of my Autumn quarter goals/ plan to meet those goals.
-   I worked on my bypass presentation for my committee meeting on Thursday.

#### Notes from 10.06.2025 Lab Meeting

::: {callout-Notes}
Goals set on 9/25/25: Have one chapter of my PhD proposal drafted and the others outlined.
:::

Progress as of 10/06/25\
After dusting off the docs and taking an inventory of where each of the pieces stand, I have the 3 PhD chapters outlined and pivoted to working on my first MS chapter. I chose to shift away from the PhD proposal focus so that I could knock out the MS chapter since it is my required manuscript for the package and needs to be reviewed/ approved by both the committee and WDFW.\

::: {callout-Notes}
My knowledge nuggets all center around things I’m using to maximize my working time and reduce the number of ‘administrative’ tasks I need to do to get rolling on the real work.
:::

> 1st- the Graduate School Funding Guide has a huge database (GFIS) of funding opportunities that you can search, download into a csv and explore on your own time. It also has the college-wide Assistantships database you can explore. There are dedicated support resources through the library if you have questions.
>
> 2nd- If you use Zotero and want to clean up your literature review process, link it to something like Notion or any other organizational platform that supports integration and keep all of your notes and annotations in one place. This video from The Grad School Coach shows you how to integrate Notion & Zotero, and this video from Aynur Science on how to create a literature review workflow using Notion that supports information recall.
>
> 3rd- Wondering where your time is going? I did my own time trials using Toggl this summer to see how long my most frequent tasks (reading and annotating a paper, coding plots, setting up data cleaning scripts, etc.) take me to complete so that I could better schedule my day and not demoralize myself when I’m not meeting my productivity goals. I used daily to track my time, help me build my weekly time blocking schedules, and review where I’m getting lost, and as a bonus, I can see just how much work on each project I am putting in and how to adjust for the upcoming week. Toggl is platform that you can use for free, but there are paid upgrades if you want them. I’ve been using it since July and haven’t needed to upgrade at all, all of the free functions are great.

::: {callout-Notes}
Goals set on 10/06 for completion by 10/20 lab meeting:\
1. Finish the biomarker manuscript 10/9\
2. Finish the committee meeting presentation 10/9\
3. Complete draft of my MS thesis 10/14\
4. Create bench protocol for Kenya samples 10/20
:::
