---
title: "Mussels, Mussels Everywhere + eDNA"
date: '2026-01-21'
categories:
  - mussel pilot experiment 
  - Kenya eDNA
  - proposal writing
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today

-   mussel pilot experiment
-   Kenya eDNA
-   proposal writing

### New Knowledge

Day 29. Mussel Check at 1813

Visual tank inspections looked good for airflow and water clarity. Mussels were still aggregated in their respective bags/ coolers. You can smell the mussels when you enter the cold room, this temperature increase may get us to 50% mortality.

-   Temperature

    -   Blue= 11° C

    -   Red= 22° C

-   Salinity

    -   Blue= 28 psu

    -   Red= 29 psu

-   Mortality

    -   Blue= 0

    -   Red= 6

-   Water Change

    -   Partial water change for Blue and Red. Salinity recheck:

        -   Blue= 25

        -   Red= 25

### Old Tricks

-   Same as 1.18, 1.19, and 1.20: Right back at it refining, aligning and ensuring my proposal is clear without getting too into the weeds. I'm super close to a draft that isn't totally embarrassing to share with the committee. I have finally finished verifying my lit, polishing what I can and have setup a schedule-send email because I do not need to share what time I finished this...

-   I met with Mollie Ball to go over the nuances between standard eDNA metabarcoding and using it for analyzing gut contents. This was super helpful and I now have a better idea of how to get my bench protocols cleaned up a bit.

### Word Count (Productivity)

-   Proposals: 938
-   **Today's total: 938 words**
-   **Monthly total to date: 7682 words**

### Questions or Concerns?

-   None.

### Tomorrow's Plan

-   Will be made tomorrow.
