---
title: "Document or it didn't happen.."
date: '2026-01-28'
categories:
  - lab_notebook
  - writing
  - notion_info_migration 
execute:
  echo: false
  warning: false
  message: false
---

### Projects Touched Today
The goal of the work today is to get my daily and weekly lab notebook back up to date! 

### New Knowledge
I created a new template that makes staging my daily and weekly posts much easier to create. My current system is to drop updates into Notion using a button, and that helps me remember days whwere one or two things were going on without a lot of detail, but this format may be an easier capture of the details that are important.

### Old Tricks
Thank goodness for the Notion setup or I would have forgotten all that has been done!

### Questions or Concerns?
Why did I keep pushing this off?!?! Definitely going to give it a better run in February.

### Tomorrow's Plan
Reviewing and updating my written proposals and figures for the biomarker manuscript will be the plan for the remainder of the week.