---
title: "Advisor 1v1: February 11, 2026"
author: "CM"
date: "2026-02-10"
categories:
  - 1v1
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    code-fold: true
---

## Agenda

1.  Update on written deliverables (MS proposal, PhD proposal, Biomarker manuscript)
2.  Mussel pilot experiment takeaways
3.  Mussel Experiment for Chapters 3 & 4
4.  DNA Methylation Analysis
5.  NW CASC Fellowship

## Updates

------------------------------------------------------------------------

### Written Deliverables

------------------------------------------------------------------------

> **MS Proposal**
>
> -   Submission deadline: February 20, 2026
> -   No committee feedback on the draft as of 2/10. Email reminder sent to committee on 2/10 extending the feedback window to 2/15.
> -   The draft can be found [at this link](https://docs.google.com/document/d/1kOuJgcRgih1GedCxO9UKK3KyOk_-YP5IIkCxGqQ-Iz0/edit?usp=drive_link).

> **PhD Proposal**
>
> -   No current submission deadline. The bypass window (2/15) is too close and no one but Alison has seen the manuscript (required in package).
> -   Goal: Have Bypass Package complete and submitted by March 13th, ahead of the May 15th deadline (next available).
> -   The draft can be found [at this link](https://docs.google.com/document/d/1kOuJgcRgih1GedCxO9UKK3KyOk_-YP5IIkCxGqQ-Iz0/edit?usp=drive_link).

> **Mussel Biomarker Manuscript**
>
> -   Submission Deadline to ICB: April 1, 2026 with preference for earlier if possible
> -   To be completed by February 15: Updated results with the corrected spatial analyses, and a complete abstract.
> -   Next steps (before committee receipt):
>     -   Add figures directly into draft
>
>     -   Put together a 'support' folder of the manuscript figures, supplementary information, and results for review with a link to the code in the existing repo.
> -   The draft can be found [at this link](https://docs.google.com/document/d/1xQPnED8yhB6x2JoCJHa0Yc5OewTkkgnT2B3yRjjQYTc/edit?usp=sharing).

------------------------------------------------------------------------

## Mussel Pilot Experiment Takeaways

------------------------------------------------------------------------

**Summary Stats**

-   Experiment Duration: 33 days (December 24, 2025 - January 25, 2026)
-   Experiment Goal: Determine mussel's in- lab thermal tolerance. Can the mussels survive for 30- days or more under chronic exposure to increasing temperatures.

[Experiment Setup]{.underline}

-   75 mussels, bagged in groups of 15, acclimated to 11° C with no food for 7 days
-   On Day 7, 45 mussels were moved to a 11° C treatment and 30 mussels were moved to a 15° C treatment; all were fed per Shellfish Diet 1800 instructions on Day 8.
-   Daily water temperature, salinity and mortality checks were performed.
-   Weekly water changes and feeding were performed
    -   Water changes were PRN, no less than once a week, and became more frequent with 20° C and 22° C temperatures.
-   Elevated temperature regime:
    -   Day 7 - 15° C

    -   Day 14 - 18° C

    -   Day 21 - 20° C

    -   Day 27 - 22° C

Experiment Outcome: 50% mortality reached in temp tx on Day 30, three days after 22° C exposure.

[Takeaways]{.underline}

-   22° C after consistent exposure to elevated temperatures is too far
-   20° C may be the maximum temperature
-   Multi- stressor experiment may require a decrease to 18° C for longevity, or 20° C (or higher) temperatures in acute exposures instead of chronic exposure

[Next Steps]{.underline}

-   Finish setting up the repo documentation.
-   Complete the resazurin analysis.

------------------------------------------------------------------------

## DNA Methylation Analysis

------------------------------------------------------------------------

> -   Status: On hold until MS Proposal submission and mussel experiment ordering/ setup is completed
> -   Anticipated Restart: February 20, 2026
> -   Plan of attack for March 15th Completion of the Steps Below:
>     -   Re-familiarize myself with where I left off in late 2025 and backup the large files.
>
>     -   Move through the initial Bismark pipeline (which I believe I finished) into optimizing alignment parameters and using that outcome for subsequent steps.
>
>     -   Quantify methylation levels and visualize using IGV or JBrowse.
>
>     -   Get feedback on initial results from Steven and/or other lab members before moving into downstream analyses.

------------------------------------------------------------------------

## Mussel Experiment for Chapters 3 & 4

------------------------------------------------------------------------

[Research Questions]{.underline}

-   How does thermal stress modify mussel physiological responses to legacy contaminant or metal exposure across environmentally relevant temperature regimes?

-   Which physiological and molecular mechanisms are associated with survival, stress tolerance, and sublethal impairment under combined legacy contaminant, metal and temperature stress?

-   Does exposure to legacy contaminants and/ or metals under elevated temperature induce changes in DNA methylation, and are differentially methylated loci associated with genes involved in stress response, detoxification, or thermal tolerance?

[Setup and Methods Overview: Ideal]{.underline}

-   Treatments (high, low and control, n=15)
    -   Temperature - 11° C and 20° C
        -   Based on pilot study thresholds
        -   Could be replaced with resazurin stress assay to simulate acute heat stress once a test run of full time to reach plateau is identified.
    -   Cadmium (metal) - low concentration & 25% above environmentally found concentrations
        -   Based on WDFW data from 2015 - 2022 and literature
    -   PAH mixture - low concentration & 25% above environmentally found concentrations at sites like Elliott Bay and Commencement Bay versus those at Hood Canal
        -   Based on WDFW data from 2015 - 2022 and literature
-   Measurements to be Taken
    -   Morphometrics - beginning and end only (LxWxH, △ weight as proxy for tissue weight)
    -   Respiration or metabolism - at timepoints defined below
    -   Biomarkers, P450 and SOD- at time points defined below
    -   Gill or mantle tissue dissection for molecular sequencing- at time points defined below
-   Experiment Duration: Minimum 30 days, Ideal- 45-60 days which is approximately 1/2 of outplanting season
-   Timepoints for Sampling (\~7)
    -   Day 0, 7, 14,21,28, 41 and end if exceeding 30 days
-   Sample Requirement: \~14lb of mussels
    -   2lbs yields \~70 mussels
    -   15 treatments requiring minimum 8 samples per timepoint (7) of destructive sampling
        -   \~840 mussels + 10% for initial condition and mortality

        -   \~930 mussels (35 mussels/ lb)

[In Progress]{.underline}

-   Lab risk assessment form from EH&S. It's diagnostic, not a requirement

-   A summary of risk and physical mitigation techniques must be on file (only part not included in standard lab handbooks/ MSDS sheets/ existing 'harmful agents' exposure protocols

-   Located chemical vendor for legacy contaminants & potential 'granting' of chemicals

    -   [Cambridge Isotope Laboratories](https://isotope.com/)

        -   [Grant request application](https://isotope.com/grant-program) (will complete regardless of choice)

        -   PAH contaminants range in price, for single agents to mixtures, from \~\$200 - \$2000 with the average mixtures running \~\$1000.

        -   An option would be to get input from Alison and Mariko (WDFW) on maybe 1-3 specifics that would cost \~\$450 (for 3).

        -   Alternatively, since PCBs are also a heavy- hitter, and skew slightly lower in price

    -   [ThermoFisher](https://www.thermofisher.com/search/browse/category/us/en/90347134) is the vendor for cadmium

        -   The formats (powder or foils?) unsure of the impact of difference

        -   No prices available without contact with them

[Next Steps]{.underline}

-   Confirm design options and requirements for moving forward
-   Connect with Jon W to assess physical setup and limitations
-   Provide a budget, supply requirements for assessment

------------------------------------------------------------------------

## NW CASC Fellowship

------------------------------------------------------------------------

> -   A version of my Chapter 3 draft can be used for this, reasoning is below application specs.
> -   Deadline for submission: March 9, 2026 The Research Fellowship call is [at this link](https://nwcasc.uw.edu/programs/research-fellowship-program/applying-for-the-research-fellowship-program/) and the pdf of the call overview is [at this link](https://github.com/ChrisMantegna/labnotebook/blob/main/weekly/2026_0210/img/RFA_2026-27-NW-CASC-Research-Fellowship-Program.pdf).
> -   Funding range: \$5,000 - \$65,000 with an averaged awarded amount of \$30,000 for graduate students (not including tuition/ fees cost) for 1 year of fellowship.
>     -   Higher amounts go to Postdocs per the fellowship FAQ/ website
> -   Full proposal requires the following pieces:
>     -   Completed online application that identifies the NW CASC Actionable Science Agenda item being addressed, specific output/ outcomes of the work, identification of external partners, requested funding and budget, and leveraged support description.
>     -   Proposal (3 page max, excluding references) with standard requirements + plan for interaction with NW CASC stakeholder (WDFW and UW-T for my thought)
>     -   Budget + Justification
>     -   Letter of support from PI
>     -   Letter of application from prospective fellow (2 page max)
>     -   Statement of Support from external partner (WDFW in accepted list)
>     -   CV of prospective fellow
> -   NW CASC Actionable Science Alignment
>     -   Managing the Ecological Impacts of Extreme Heat in the Northwest ([*ActionableScience Agenda^5^*](https://github.com/ChrisMantegna/labnotebook/blob/main/weekly/2026_0210/img/Managing-the-Ecological-Impacts-of-Extreme-Heat-in-the-Northwest.pdf))
>         -   [Key Research Needs]{.underline}: Ranked from most applicable to least
>
>         -   Characterize the interactive ecological effects of extreme heat and other anthropogenic, biotic and abiotic disturbances and stressors
>
>         -   Assess and improve the effectiveness and accessibility of existing tools to measure and predict general and extreme heat exposure and impacts
>
>         -   Understand the mechanisms and drivers of interspecific and intraspecific variation in sensitivity and adaptive capacity to extreme heat
>
>         -   [Key Capacity- building Needs]{.underline}: Ranked from most applicable to least
>
>         -   Improve, operationalize and expand the accessibility of existing tools and datasets
>
>         -   Support long-term and post-event rapid ecological and microclimate monitoring
>     -   Priority ecosystem: Coastal
>         -   [Marine coastlines and nearshore habitats]{.underline}, Rocky intertidal zones, Estuaries, Sandy coastlines
>     -   Climate-Linked Drivers of Ecological Change
>         -   Increasing Temperatures: [Warmer winters, summer heat extremes and heat domes]{.underline}, changes in growing seasons
>
>         -   Land use changes and additional stressors categories may also apply
>
> [Next Steps]{.underline}
>
> -   Info-session on Thursday 2/12- I am registered and will attend.
