---
title: "Conservation Ecology & DNA Methylation "
date: "2026-03-26"
categories:
  - NWStraits Symposium
  - DNA Methylation
  - Conservation Ecology
execute:
  echo: false
  warning: false
  message: false

editor:
  markdown:
    wrap: 72
---

### Plan of the Week: March 23 - 27, 2026

#### *High- level outline for the week. Adjusted daily to reflect progress of the day before*

-   I am still not at full capacity and my plan for the week is to map
    out the rest of March and Spring Quarter since I have some very
    real, very important deadlines I'd like to hit.

------------------------------------------------------------------------

<div>

> ~~Monday - Catch up on UW-RUA and science project planning~~
>
> ~~Tuesday - Planning & biomarker manuscript work~~
>
> ~~Wednesday - Biomarker Manuscript~~
>
> Thursday - Chapter 3 proposal
>
> Friday - Chapter 3 proposal
>
> Saturday - Biomarker Manuscript
>
> Sunday - Weekly planning and prep

</div>

------------------------------------------------------------------------

### Plan of the Day

#### *Granular level task list to accomplish the high- level goal outlined above*

-   Today's goal is to complete the followings:
    -   NWStraits abstract and poster mock-up
    -   Locate open source sequences for Chapter 3
    -   Update or refine and add my figures to the biomarker manuscript
    -   Prep for my meeting with PSP and Tiara for the social science
        project
    -   Complete the task mapping for the lower-priority projects

### Projects Touched Today

-   DNA Methylation
-   NWStraits Caroline Gibson Conservation Symposium
-   Conservation Ecology

------------------------------------------------------------------------

### Progress Notes

-   I knocked out my abstract and followed up with my current and former
    mentees to remind them to get the requested information to me by the
    end of their day on Friday.
    -   My poster is about increasing access to increase larger
        opportunities in conservation ecology
    -   The plan is to link programs like Yellow, REU, and DDCSP to
        their larger impacts in conservation
-   Somehow, I managed to lock up Raven on my end. I thought the
    additional script I started yesterday was MultiQC only, not the
    alignment script, and that caused everything to just hang in the
    air.
    -   I force- quit all terminals running
    -   I attempted to commit the files that I changed and managed to
        stare at a 'commit' screen that would not respond to any
        staging. I realized far too late that I checked one of the huge
        packages with about a gazillion parts while I was clicking
        around to see if I had just lost my mouse or if the interface
        was lagging...
    -   Now, I can't get Raven to load without crazy lagging - I haven't
        waited this long to accomplish anything since dial-up days- so I
        know I screwed something up on my side.
    -   I have shut it all down, killed all processes, and am going to
        restart it after my afternoon meeting.
-   I added a timeline, products, notes, and a revised research question
    section to my proposal idea with PSP.
    -   Tiara and BIMS will be the non-profit partner with me as the
        lead researcher - if our proposal is accepted.
    -   Next steps are to polish the plan slightly for the next meeting
        with PSP, BIMS and WA SeaGrant to ensure we are aligned in the
        mission.
-   Next up, finding RNA-seq in NCBI for some gene expression and mussel
    methylation comparisons for Chapter 3.
    -   I created a Bookmarked folder of all 47 of the SRAs and GEO
        datasets for *Mytilus* spp., focusing on RNA-seq data in mantle
        tissue, including both non-stressed and treatment stressed
        samples. I then added a few that were other tissue types just in
        case. As a reminder, I chose mantle tissue because that is the
        tissue type I am exploring in the methylation analysis.
    -   I read the abstracts to confirm data type, treatment, and
        preparation process. Anything without an abstract was flagged
        for removal.
    -   I started working my way through a quick skim of the methods
        section of papers related to the sequences so I can confirm
        fully the availability, sequencing platform, and sample
        preparation process. This helped me flag those prepared for
        immuno-assays and immune function chromosome tags that weren't
        clear in the abstract nor the sequence name in the NCBI
        databases.
    -   I set a 90 minute time block on this, so I marked where I left
        off, and will return during another 'transition task' work
        block.
-   Returning to Raven. I had to reach out to Sam to kill anything I had
    going on because I very effectively put a pause on the work...
    -   I dug a bit more and realized it was a GitHub issue - one cannot
        simply commit using terminal and then attempt to push or pull
        with the interface without creating an issue..
    -   Once I solved my issue, I cleaned out the old mussel methylation
        repo taking up huge space, cleaned up my commit, and restarted
        Raven.
    -   Success was getting my MultiQC reports for the raw and trimmed
        files after looping through the output folders to ensure the
        downloads, checksums, and trimmed files existed with their
        respective FastQC files.
    -   I moved over to running the full alignments with Bismark after
        verifying that the reference was downloaded, checksum match
        confirmed, and Bismark bisulfite genome created. Now we wait...
-   I brainstormed some ideas for the Black Opportunity Fund call,
    something art and environment related.
    -   Put out a few feelers for artists, branding/ marketing, and
        venues.
-   I started pulling together all of my project notes for the 3
    projects I have listed on my lab notebook site
    -   Biomarkers- Google docs analysis notes doc
    -   Methylation - will need to pull from daily notebook posts
    -   Yellow - my UW Google drive, my personal Google drive, and daily
        posts.
    -   I'm certain the handwritten notes on all projects won't make it
        in for now, but will be in future projects because I just don't
        want to waste time pulling them for projects reaching their end.
-   I wrapped up the day by updating my CV using Vitae and finally
    getting to my About Me GitHub page since I will be presenting myself
    and my work in 2 weeks and I'd like folks to have something more
    substantial than my GH landing page only.

------------------------------------------------------------------------

### Outcomes: Products & Word Count

-   NWStraits Abstract: 107 words
-   PSP Social Science Proposal Update: 412 words
-   BOP Art x Environmentalism Ideas: 277 words
-   Creating my About Me .qmd page: 528 words
-   NWStraits poster mock-up based on mentee responses so far

<div>

> **Today's total: 1324 words**
>
> **Monthly total to date: 10,399 words**
>
> **Annual total to date: 32,094 words**
>
> **Annual target total to date: 42,500 words**

</div>

### Next Up: Tomorrow's Plan

-   Will be determined by the end of the day!
