---
title: "Advisor Working Session: April 29, 2026"
date: "2026-04-27"
categories:
  - 1v1
  - Working Session
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    code-fold: true
---

------------------------------------------------------------------------

### Agenda

------------------------------------------------------------------------

1.  Updates

    1.  Biomarker Manuscript

2.  Methylation Results and Methods Drafting

------------------------------------------------------------------------

### Updates 1: Biomarker Manuscript

------------------------------------------------------------------------

> Status: Emailed draft on 4/18 to Steven only
>
> Added to Google Drive on 4.19.26 when the WiFi was stable

------------------------------------------------------------------------

### Item 2: Methylation Methods Drafting

------------------------------------------------------------------------

> This is the [link to the drafted Methods Section](https://docs.google.com/document/d/1nSLnD8NJy9VPjAOi8iKxrFMQQo67Cwf2/edit?usp=sharing&ouid=117330698960206374690&rtpof=true&sd=true).
>
> Status: Initial draft

------------------------------------------------------------------------

### Item 2: Methylation Results Drafting

------------------------------------------------------------------------

> I put together the table of DMLs from your 1055.tab file.
>
> The quick stats are below from my 4/15 Daily Post
>
> -   The annotated gene list is in [Steven's notebook post](https://sr320.github.io/tumbling-oysters/posts/36-merry/). A quick review shows the following:
>     -   12 of 17 DMLs mapped to genes that are hypo-, hyper- methylated, or both.
>     -   4 are hyper-methylated, 6 are hypo-methylated, and 2 have both instances.
>     -   The magnitudes of methylation in either direction are the same.
>     -   10/12 have a characterized gene function, and 2/10 are uncharacterized.

------------------------------------------------------------------------

### Item 2...

------------------------------------------------------------------------

Things about the topic

------------------------------------------------------------------------

### Item 3...

------------------------------------------------------------------------

### Deliverables for Next Week

------------------------------------------------------------------------

> Next Meeting: May 5th @ 10:30am
>

